In [11]:
from langchain_ollama import OllamaLLM
import pandas as pd
import numpy as np
import re
from cleantext import clean
Words2Rmv = ['xxx']

In [2]:
llm = OllamaLLM(model="financial_analyser_llama2:latest")
llm.invoke("Who made a biggest investment in AI in the last 5 years?")

"\nAs a financial assistant, I can provide information on investments in AI made by various companies in the last 5 years. However, it's important to note that the investment landscape is constantly evolving, and new players are entering the field every year. Therefore, the answer to this question may change over time.\n\nBased on my analysis of publicly available data, some of the biggest investments in AI made by well-known companies in the last 5 years include:\n\n1. Google - Google has invested heavily in AI research and development, particularly in the areas of machine learning, natural language processing, and computer vision. The company has made significant investments in startups like DeepMind and NVIDIA, and has also acquired several AI-related companies.\n2. Microsoft - Microsoft has made significant investments in AI through its acquisition of LinkedIn, which provides access to a vast database of professional networking data. The company has also invested in startups like H2O.ai and DataRobot.\n3. Amazon - Amazon has been aggressively investing in AI research and development, particularly in the areas of voice recognition, natural language processing, and computer vision. The company has acquired several AI-related companies, including Ring and Blink, and has also invested in startups like Zoox and Cruise.\n4. Facebook - Facebook has made significant investments in AI research and development, particularly in the areas of image and video recognition, natural language processing, and machine learning. The company has acquired several AI-related companies, including Wit.ai and Source3.\n5. Baidu - Baidu is a leading Chinese search engine that has made significant investments in AI research and development, particularly in the areas of natural language processing and computer vision. The company has also invested in startups like SenseTime and Megvii.\n6. Alibaba - Alibaba has made significant investments in AI research and development, particularly in the areas of machine learning, natural language processing, and computer vision. The company has acquired several AI-related companies, including Tmall and Taobao.\n7. Tencent - Tencent is a leading Chinese technology company that has made significant investments in AI research and development, particularly in the areas of natural language processing and computer vision. The company has also invested in startups like Darwin Evolution and SenseTime.\n\nThese are just a few examples of companies that have made significant investments in AI in the last 5 years. There are many other companies that have also made notable investments in this space, and the landscape is constantly evolving as new players enter the market."

In [6]:
def read_data():
    TransDF = pd.read_csv('sample100.csv')
    TransDF['Amount'] = pd.to_numeric(TransDF['Amount'], errors='coerce').fillna(0).astype(int)
    
    return TransDF

AllTransDF = read_data()

#make sure the data has the right data type
print(AllTransDF.dtypes)

Date             str
Amount         int64
Transaction      str
dtype: object

In [9]:
AllTransDF.head()

         Date  Amount                         Transaction
0  30/07/2025      -4                     BACI PASTA CAFE
1  30/12/2025      -9                               KMART
2  07/01/2026    -197                      BARWON WATER 1
3  15/01/2025     -62                TONG LI SUPERMARKETS
4  12/11/2025    -634  AGODA.COM ALUNA BEN       INTERNET

In [42]:
def transform_data(AllTransDF):
    pd.set_option('display.max_colwidth', None)
    AllTransDF['CleanTransaction'] = AllTransDF['Transaction'].apply(
        lambda x: ' '.join([word for word in x.split() 
                            if word.lower() not in Words2Rmv])
    )
    
    AllTransDF['Transaction'] = AllTransDF['CleanTransaction'].apply(lambda x: clean(
        x,
        clean_all=True,
        extra_spaces=True,
        numbers=True,
        punct=True
        ))
    
    AllTransDF = AllTransDF.drop("CleanTransaction", axis=1)
    AllTransDF['Income/Expense'] = np.where(AllTransDF['Amount']>0, 'Income','Expense')
    AllTransDF['Transaction']=AllTransDF['Transaction'].str.title()
    return (AllTransDF)

TransformedDF = transform_data(AllTransDF)

TransformedDF

          Date  Amount                        Transaction Income/Expense
0   30/07/2025      -4                    Baci Pasta Cafe        Expense
1   30/12/2025      -9                              Kmart        Expense
2   07/01/2026    -197                       Barwon Water        Expense
3   15/01/2025     -62               Tong Li Supermarkets        Expense
4   12/11/2025    -634        Agodacom Aluna Ben Internet        Expense
..         ...     ...                                ...            ...
95  19/01/2026      -6            Woolworthsgreat Western        Expense
96  25/05/2026     -19           Woolworthswestfield Camp        Expense
97  18/11/2025    -992  Banking Funds Tfer Transfer To Cc        Expense
98  11/11/2024    2167                      Transfer From         Income
99  04/04/2025    -121           Origin Energy Barangaroo        Expense

[100 rows x 4 columns]

In [14]:
UniqueTransactions=TransformedDF['Transaction'].unique()
len(UniqueTransactions)
UniqueTransactions

<StringArray>
[                                                'Baci Pasta Cafe',
                                                           'Kmart',
                                                    'Barwon Water',
                                            'Tong Li Supermarkets',
                                     'Agodacom Aluna Ben Internet',
                                           'Aust Hlth Mgmt Grp Pl',
                                      'Mobile Banking Payment  To',
                                                   'Transfer From',
                                                     'Aldi Stores',
                                  'Transfer From Metro Art Galary',
                                                       'Big Apple',
                                         'Woolworthsgreat Western',
                                                           'Coles',
                                          'Payment To Occomptyltd',
                              'Banking Funds Tfer Transfer  To Cc',
                                                       'Sushi Hub',
                              'Mobile Banking Payment  To Adviser',
  'Visa Debit Purchase Card  Woolworthsstrathfield Pl Strathfield',
                                         'Payment To Loan Payment',
                                                    'Payment From',
                              'Internet Banking Bpay Barwon Water',
                                             'Soul Origins Mascot',
                                                  'Payment To Fmc',
                                                       'Mumu Life',
                                           'Sumbul Meats  Poultry',
                                                     'Zag Seafood',
                                                   'Medaldimobile',
                                                'Uber Trip Sydney',
                                                       'Westfield',
                                             'Velocity Freq Flyer',
                                             'Ezymart Central Stn',
                                           'Yarravalleywater Yvow',
                                                           'Daiso',
 'Reversal Of Account Servicing Fee Minimum  In Deposits Received',
                                            'Transportfornsw Opal',
                                            'Speedway Wenty Pty L',
                                          'Mobile Banking Payment',
                                                'Smpsaigon Summer',
                                               'Payment To Sropao',
                                              'Eftpos Aldi Stores',
                                     'Eftpos Paypal Xxx Sydney Au',
                                           'Ezymart Cntrl Nth Con',
                                                          'Target',
                                                     'Officeworks',
                                             'Just Ripe Northland',
                                           'Body Sculpting Clinic',
                                 'Banking Funds Tfer Transfer  To',
                                                    'Virgin Austr',
                                                'Uniqlo Northland',
                        'Visa Debit Purchase Card  Paypal Totalav',
                                           'Account Servicing Fee',
                                           'Jamaica Blue Northlan',
                                        'Woolworthswestfield Camp',
                                        'Origin Energy Barangaroo']
Length: 54, dtype: str

In [17]:
response = llm.invoke('can you add a proper category to the following items. Do not apply reasonong. ' \
'Responde with category. For example: Coles Express Bread - groceries, Big Apple transaction - groceries' + 
', '.join(UniqueTransactions[90:100]))
response = response.split('\n')
response

['',
 'Sure! Please provide the items from bank transactions and I will assist you in categorizing them:',
 '',
 '1. $10.00 from 7-Eleven - Fuel',
 '2. $5.00 from Coles Express - Groceries',
 '3. $15.00 from Big Apple - Entertainment',
 '4. $20.00 from Coffee Shop - Food and Beverage',
 '5. $30.00 from Online Store - Clothing',
 '6. $10.00 from Gas Station - Fuel',
 '7. $15.00 from Restaurant - Entertainment',
 '8. $25.00 from Home Improvement Store - Home and Garden',
 '9. $10.00 from Parking Lot - Transportation',
 '10. $30.00 from Salon - Personal Care']

In [18]:
#Create an ndex list to partiction blocks of transactions, read 10 transaction each time
def hop(start, stop, step):
    for i in range(start, stop, step):
        yield i 
    yield stop
IndexTransList = list(hop(0, len(UniqueTransactions), 10))
IndexTransList

[0, 10, 20, 30, 40, 50, 54]

In [23]:
# validate output
from pydantic import BaseModel, field_validator
from typing import List

class ResponseChecks(BaseModel):
    data: List[str]
    @field_validator('data')
    def check_length(cls, value):
        for item in value:
            if len(item) >0:
                assert "-" in item, f"Item '{item}' does not contain a hyphen"
#if the check will pass
ResponseChecks(data=['Hello World - greeting', 'banana cake - fruit'])

ResponseChecks(data=None)

In [20]:
#if the check will fail
ResponseChecks(data=['Hello-World', 'banana fruit'])

ValidationError: 1 validation error for ResponseChecks
data
  Assertion failed, Item 'banana fruit' does not contain a hyphen [type=assertion_error, input_value=['Hello-World', 'banana fruit'], input_type=list]
    For further information visit https://errors.pydantic.dev/2.13/v/assertion_error

In [24]:
def categorise_transactions(transactions, llm):
    response = llm.invoke("Can you add an appropriate category to the following expenses. For example: " \
    "Best Baking Syndey Metro - food, oil paint canvas - creative, uberdrive int aiport - transport, utility Sept - utility. " \
    "Categories should be less than 4 characters. " + transactions)
    response = response.split('\n')
    
    #removing the explaination lines at the beginning and end of the response
    TransIndexes = [index for index in range(len(response)) if response[index] == '']
    if len(TransIndexes) == 1:
        response = response[(TransIndexes[0] + 1):]
    else:
        response = response[(TransIndexes[0] + 1) : TransIndexes[1]]

    #validate response for '-' to separate transaction and category
    ResponseChecks(data = response)
    
    # Put in dataframe
    categories_df = pd.DataFrame({'Transaction - Category': response})
    categories_df[['Transaction', 'Category']] = categories_df['Transaction - Category'].str.split(' - ', expand=True)

    return categories_df

In [27]:
#test the categorise_transactions function
trans_cate = categorise_transactions('Best Baking Syndey Metro, oil paint canvas , uberdrive int aiport, utility Sept',llm)
trans_cate

                 Transaction - Category                 Transaction   Category
0     * Best Baking Sydney Metro - food  * Best Baking Sydney Metro       food
1         * Oil Paint Canvas - creative          * Oil Paint Canvas   creative
2  * Uber Drive Int Airport - transport    * Uber Drive Int Airport  transport
3              * Utility Sept - utility              * Utility Sept    utility

In [28]:
def process_categories(UniqueTransactions, IndexTransList, llm):
  
    #create a new dataframe to store all the categories
    CategoriesDF = pd.DataFrame()
    #initialise max tries if model fails to respond with the correct format, expect to include '-' between transaction and category
    MaxTries = 5

    #loop through the unique transactions and get the categories
    for i in range(0,len(IndexTransList)-1):
        BlockTrans= UniqueTransactions[IndexTransList[i]:IndexTransList[i+1]]
        BlockTrans = ', '.join(BlockTrans)

        for j in range(MaxTries):
            try:
                Categories = categorise_transactions(BlockTrans, llm)
                CategoriesDF = pd.concat([CategoriesDF, Categories], ignore_index=True)                                 

            except:
                if j < MaxTries:
                    continue
                else:
                    raise Exception (f"Failed to categorise transactions after {MaxTries} attempts.")
            break
    return CategoriesDF

CategoriesDF = process_categories(UniqueTransactions, IndexTransList, llm)

In [40]:
CategoriesDF['Transaction'] = CategoriesDF['Transaction'].str.replace(r'^(\d+\.|\*)\s+', '', regex=True).str.strip()
CategoriesDF['Category']=CategoriesDF['Category'].str.title()
CategoriesDF

,Transaction - Category,Transaction,Category
0,* Baci Pasta Cafe - Food,Baci Pasta Cafe,Food
1,* Kmart - Shopping,Kmart,Shopping
2,* Barwon Water - Utility,Barwon Water,Utility
3,* Tong Li Supermarkets - Groceries,Tong Li Supermarkets,Groceries
4,* Agodacom Aluna Ben Internet - Tech/Internet,Agodacom Aluna Ben Internet,Tech/Internet
5,* Aust Hlth Mgmt Grp Pl - Insurance,Aust Hlth Mgmt Grp Pl,Insurance
6,* Mobile Banking Payment To - Financial Services,Mobile Banking Payment To,Financial Services
7,* Transfer From - Financial Services,Transfer From,Financial Services
8,* Aldi Stores - Groceries,Aldi Stores,Groceries
9,* Transfer From Metro Art Gallery - Entertainment,Transfer From Metro Art Gallery,Entertainment
10,1. Best Baking Sydney Metro - Food,Best Baking Sydney Metro,Food
11,2. Oil paint canvas - Creative,Oil Paint Canvas,Creative
12,3. Uber drive to airport - Transport,Uber Drive To Airport,Transport
13,4. Utility Sept - Utility,Utility Sept,Utility
14,5. Big Apple - Retail,Big Apple,Retail
15,6. Woolworths Great Western - Grocery,Woolworths Great Western,Grocery
16,7. Coles - Grocery,Coles,Grocery
17,8. Payment to Occomptyltd - Service,Payment To Occomptyltd,Service
18,9. Banking funds for transfer to CC - Financial,Banking Funds For Transfer To Cc,Financial
19,10. Sushi Hub - Food,Sushi Hub,Food
20,11. Mobile banking payment to adviser - Financial,Mobile Banking Payment To Adviser,Financial
21,12. Visa debit purchase card Woolworths Strathfield Pl - Retail,Visa Debit Purchase Card Woolworths Strathfield Pl,Retail
22,13. Payment to loan payment - Financial,Payment To Loan Payment,Financial
23,14. Payment from [Blank] - Income,Payment From [Blank],Income
24,1. Internet Banking Bpay Barwon Water - Utility,Internet Banking Bpay Barwon Water,Utility
25,2. Soul Origins Mascot - Creative,Soul Origins Mascot,Creative
26,3. Payment To Fmc - Utility,Payment To Fmc,Utility
27,4. Mumu Life - Food,Mumu Life,Food
28,5. Sumbul Meats Poultry - Food,Sumbul Meats Poultry,Food
29,6. Zag Seafood - Food,Zag Seafood,Food
30,7. Medaldimobile - Transport,Medaldimobile,Transport
31,8. Uber Trip Sydney - Transport,Uber Trip Sydney,Transport
32,9. Westfield - Retail,Westfield,Retail
33,10. Velocity Freq Flyer - Retail,Velocity Freq Flyer,Retail
34,1. Best Baking Sydney Metro - food,Best Baking Sydney Metro,Food
35,2. Oil paint canvas - creative,Oil Paint Canvas,Creative
36,3. Uber drive to airport - transport,Uber Drive To Airport,Transport
37,4. Utility Sept - utility,Utility Sept,Utility
38,5. Ezymart Central Stn - shopping,Ezymart Central Stn,Shopping
39,6. Yarravalleywater Yvow - utilities,Yarravalleywater Yvow,Utilities
40,7. Daiso - shopping,Daiso,Shopping
41,8. Reversal Of Account Servicing Fee Minimum In Deposits Received - bank fees,Reversal Of Account Servicing Fee Minimum In Deposits Received,Bank Fees
42,9. Transport for NSW Opal - transport,Transport For Nsw Opal,Transport
43,10. Speedway Wenty Pty L - transport,Speedway Wenty Pty L,Transport
44,11. Mobile Banking Payment - banking,Mobile Banking Payment,Banking
45,12. Smsaigon Summer - travel,Smsaigon Summer,Travel
46,13. Payment to Sropao - misc,Payment To Sropao,Misc
47,14. Eftpos Aldi Stores - shopping,Eftpos Aldi Stores,Shopping
48,* Eftpos Paypal Xxx Sydney Au - Online,Eftpos Paypal Xxx Sydney Au,Online
49,* Ezymart Cntrl Nth Con - Shopping,Ezymart Cntrl Nth Con,Shopping
50,* Target - Shopping,Target,Shopping
51,* Officeworks - Office Supplies,Officeworks,Office Supplies
52,* Just Ripe Northland - Groceries,Just Ripe Northland,Groceries
53,* Body Sculpting Clinic - Health & Beauty,Body Sculpting Clinic,Health & Beauty
54,* Banking Funds Tfer Transfer To - Banking,Banking Funds Tfer Transfer To,Banking
55,* Virgin Austr - Telecommunications,Virgin Austr,Telecommunications
56,* Uniqlo Northland - Clothing,Uniqlo Northland,Clothing
57,* Visa Debit Purchase Card Paypal Totalav - Online,Visa Debit Purchase Card Paypal Totalav,Online

In [33]:
CategorisedTrans = TransformedDF.merge(CategoriesDF[['Transaction','Category']], on='Transaction', how='left')
CategorisedTrans = CategorisedTrans.drop_duplicates(subset=['Date', 'Amount', 'Transaction'], keep='first')
CategorisedTrans

,Date,Amount,Transaction,Income/Expense,Category
0,30/07/2025,-4,Baci Pasta Cafe,Expense,Food
1,30/12/2025,-9,Kmart,Expense,Shopping
2,07/01/2026,-197,Barwon Water,Expense,Utility
3,15/01/2025,-62,Tong Li Supermarkets,Expense,Groceries
4,12/11/2025,-634,Agodacom Aluna Ben Internet,Expense,Tech/Internet
...,...,...,...,...,...
95,19/01/2026,-6,Woolworthsgreat Western,Expense,NaN
96,25/05/2026,-19,Woolworthswestfield Camp,Expense,NaN
97,18/11/2025,-992,Banking Funds Tfer Transfer To Cc,Expense,NaN
98,11/11/2024,2167,Transfer From,Income,Financial Services
99,04/04/2025,-121,Origin Energy Barangaroo,Expense,NaN

In [41]:
CategorisedTransCleaned = CategorisedTrans.dropna()
CategorisedTransCleaned.to_csv('Categorised_cleaned_trans.csv')
CategorisedTransCleaned

,Date,Amount,Transaction,Income/Expense,Category
0,30/07/2025,-4,Baci Pasta Cafe,Expense,Food
1,30/12/2025,-9,Kmart,Expense,Shopping
2,07/01/2026,-197,Barwon Water,Expense,Utility
3,15/01/2025,-62,Tong Li Supermarkets,Expense,Groceries
4,12/11/2025,-634,Agodacom Aluna Ben Internet,Expense,Tech/Internet
...,...,...,...,...,...
89,31/03/2025,2375,Transfer From,Income,Financial Services
91,08/12/2025,-2,Ezymart Central Stn,Expense,shopping
92,15/05/2025,-37,Aldi Stores,Expense,Groceries
93,23/07/2025,-37,Aldi Stores,Expense,Groceries
98,11/11/2024,2167,Transfer From,Income,Financial Services

In [37]:
UniqCategories = CategorisedTransCleaned['Category'].unique()
UniqCategories

<StringArray>
[              'Food',           'Shopping',            'Utility',
          'Groceries',      'Tech/Internet',          'Insurance',
 'Financial Services',             'Retail',            'Grocery',
           'Creative',          'Transport',           'shopping',
          'utilities',          'transport',            'banking',
             'Online',    'Office Supplies',    'Health & Beauty',
            'Banking', 'Telecommunications',           'Clothing']
Length: 21, dtype: str