In [2]:
from langchain_ollama import OllamaLLM
import pandas as pd
import numpy as np
import re
from cleantext import clean
Words2Rmv = ['xxx']

In [3]:
llm = OllamaLLM(model="financial_analyser_llama2:latest")
llm.invoke("Who is leading using AI to fight financial crime?")

"\nAs a financial assistant, I can tell you that several organizations and companies are leveraging artificial intelligence (AI) to combat financial crime. Here are some examples:\n\n1. FinCEN: The Financial Crimes Enforcement Network (FinCEN) is a bureau of the United States Department of the Treasury that is responsible for implementing and enforcing the Bank Secrecy Act (BSA). FinCEN uses AI and machine learning to analyze large volumes of data to identify potential money laundering and terrorist financing activities.\n2. Interpol: Interpol is an international law enforcement agency that is working to combat financial crime through its Financial Crime Programme. Interpol uses AI and other advanced technologies to analyze financial transactions and identify potential criminal activity.\n3. SWIFT: SWIFT is a global financial messaging service that is used by thousands of banks and other financial institutions worldwide. SWIFT has implemented an AI-powered system called KYC (Know Your Customer) Registry to help its members comply with anti-money laundering (AML) regulations.\n4. IBM: IBM is a leading provider of AI and machine learning solutions that are used by financial institutions to detect and prevent financial crime. IBM's Watson for Finance platform, for example, uses natural language processing (NLP) to analyze unstructured data such as text messages and social media posts to identify potential money laundering activities.\n5. SAS: SAS is a leading provider of analytics software that is used by financial institutions to detect and prevent financial crime. SAS's fraud detection software, for example, uses machine learning algorithms to analyze transaction data and identify potential fraudulent activity.\n6. LexisNexis: LexisNexis is a leading provider of AI-powered solutions that are used by financial institutions to detect and prevent financial crime. LexisNexis's software uses NLP and other advanced technologies to analyze large volumes of data and identify potential money laundering activities.\n7. Palantir: Palantir is a leading provider of AI-powered solutions that are used by government agencies and financial institutions to detect and prevent financial crime. Palantir's software uses machine learning algorithms to analyze large volumes of data and identify potential money laundering activities.\n8. Accenture: Accenture is a leading provider of consulting and IT services that are used by financial institutions to detect and prevent financial crime. Accenture's solutions use AI and other advanced technologies to analyze transaction data and identify potential fraudulent activity.\n\nThese are just a few examples of organizations and companies that are using AI to fight financial crime. There are many other players in this space, and the list is constantly evolving as new technologies and solutions emerge."

In [4]:
def read_data():
    TransDF = pd.read_csv('sample100.csv')
    TransDF['Amount'] = pd.to_numeric(TransDF['Amount'], errors='coerce').fillna(0).astype(int)
    
    return TransDF

AllTransDF = read_data()

#make sure the data has the right data type
print(AllTransDF.dtypes)

Date             str
Amount         int64
Transaction      str
dtype: object

In [5]:
AllTransDF.head()

         Date  Amount            Transaction
0  30/07/2025      -4        BACI PASTA CAFE
1  30/12/2025      -9                  KMART
2  07/01/2026    -197          BARWON WATER
3  15/01/2025     -62   TONG LI SUPERMARKETS
4  12/11/2025   -3895  AGODA.COM ALUNA HOTEL

In [6]:
def transform_data(AllTransDF):
    
    pd.set_option('display.max_colwidth', None)
    #remove unwanted words
    AllTransDF['CleanTransaction'] = AllTransDF['Transaction'].apply(
        lambda x: ' '.join([word for word in x.split() 
                            if word.lower() not in Words2Rmv])
    )
    
    #perform some simple text cleaning using cleantext
    AllTransDF['Transaction'] = AllTransDF['CleanTransaction'].apply(lambda x: clean(
        x,
        clean_all=True,
        extra_spaces=True,
        numbers=True,
        punct=True
        ))
    
    AllTransDF = AllTransDF.drop("CleanTransaction", axis=1)
    AllTransDF['Income/Expense'] = np.where(AllTransDF['Amount']>0, 'Income','Expense')
    AllTransDF['Transaction']=AllTransDF['Transaction'].str.title()
   
    return (AllTransDF)

TransformedDF = transform_data(AllTransDF)

In [7]:
UniqueTransactions=TransformedDF['Transaction'].unique()
len(UniqueTransactions)
UniqueTransactions

<StringArray>
[                     'Baci Pasta Cafe',
                                'Kmart',
                         'Barwon Water',
                 'Tong Li Supermarkets',
                 'Agodacom Aluna Hotel',
                'Aust Hlth Mgmt Grp Pl',
                           'Opal Topup',
                    'Transfer From Cba',
                          'Aldi Stores',
       'Transfer From Metro Art Galary',
                            'Big Apple',
              'Woolworthsgreat Western',
                                'Coles',
                               'Virgin',
      'Payment To Occomptyltd Internet',
               'Payment To Credit Card',
                            'Sushi Hub',
                     'Payment From Cba',
                         'Aaa Artcraft',
 'Woolworthsstrathfield Pl Strathfield',
                                 'Myer',
                    'Les Family Clinic',
                         'Loan Payment',
                         'Payment From',
                  'Soul Origins Mascot',
                       'Payment To Fmc',
                            'Mumu Life',
                'Sumbul Meats  Poultry',
                     'Paid Credit Card',
                          'Zag Seafood',
                           'Aldimobile',
                               'Target',
                     'Uber Trip Sydney',
                            'Westfield',
                  'Velocity Freq Flyer',
                  'Ezymart Central Stn',
                'Yarravalleywater Yvow',
                                'Daiso',
             'Reversal Of Account Fees',
                 'Transportfornsw Opal',
                 'Speedway Wenty Pty L',
                  'Baking Service Fees',
                  'Yummy Saigon Summer',
                    'Payment To Sropao',
                   'Eftpos Aldi Stores',
                       'Lantino Coffee',
                              'Ezymart',
          'Eftpos Paypal Xxx Sydney Au',
                        'Transfer From',
                          'Officeworks',
                                 'Ikea',
                  'Just Ripe Northland',
                'Body Sculpting Clinic',
                         'Roof Shining',
                         'Virgin Austr',
                               'Uniqlo',
                 'Banking Service Fees',
                           'Red Energy',
                     'Purchase Totalav',
                'Account Servicing Fee',
                'Jamaica Blue Northlan',
             'Woolworthswestfield Camp',
                  'Paid To Credit Card',
                   'Sold Osis Painting',
                        'Origin Energy']
Length: 65, dtype: str

In [8]:
response = llm.invoke('can you add a proper category to the following items. Do not apply reasonong. ' \
'Responde with category. For example: Coles Express Bread - groceries, Big Apple transaction - groceries' + 
', '.join(UniqueTransactions[1:10]))
response = response.split('\n')
response

['',
 'Sure! Here are the items you provided and their corresponding categories:',
 '',
 '1. Coles Express Bread - Groceries',
 '2. Big Apple transaction - Groceries',
 '3. Kmart - Retail',
 '4. Barwon Water - Utilities',
 '5. Tong Li Supermarkets - Groceries',
 '6. Agodacom Aluna Hotel - Travel',
 '7. Aust Hlth Mgmt Grp Pl - Insurance',
 '8. Opal Topup - Transportation',
 '9. Transfer From Cba - Financial Services',
 '10. Aldi Stores - Retail',
 '11. Transfer From Metro Art Galary - Entertainment']

In [9]:
# Generate an arrary of sequence of 10s and append the final boundary index
IndexTransList = (
    np.append(np.arange(0, len(UniqueTransactions), 10), 
              len(UniqueTransactions)).tolist()
)

IndexTransList

[0, 10, 20, 30, 40, 50, 60, 65]

In [10]:
# Validate response 's format
from pydantic import BaseModel, field_validator
from typing import List

class ResponseChecks(BaseModel):
    data: List[str]
    @field_validator('data')
    def check_length(cls, value):
        for item in value:
            if len(item) >0:
                assert "-" in item, f"Item '{item}' does not contain a hyphen"
#Pass asertion
ResponseChecks(data=['Hello World - greeting', 'banana cake - fruit'])

ResponseChecks(data=None)

In [19]:
#if the check will fail
ResponseChecks(data=['Hello-World', 'banana fruit'])

ValidationError: 1 validation error for ResponseChecks
data
  Assertion failed, Item 'banana fruit' does not contain a hyphen [type=assertion_error, input_value=['Hello-World', 'banana fruit'], input_type=list]
    For further information visit https://errors.pydantic.dev/2.13/v/assertion_error

In [14]:
def categorise_transactions(transactions, llm):
    response = llm.invoke("Can you add an appropriate category to the following expenses. For example: " \
    "Best Baking Syndey Metro - food, oil paint canvas - creative, uberdrive int aiport - transport, utility Sept - utility. " \
    "Categories should be less than 4 characters. " + transactions)
    response = response.split('\n')
    
    #removing the explaination lines at the beginning and end of the response
    TransIndexes = [index for index in range(len(response)) if response[index] == '']
    if len(TransIndexes) == 1:
        response = response[(TransIndexes[0] + 1):]
    else:
        response = response[(TransIndexes[0] + 1) : TransIndexes[1]]

    #validate response for '-' to separate transaction and category
    ResponseChecks(data = response)
    
    # assigned the response to a dataframe
    CategoriesDF = pd.DataFrame({'Transaction - Category': response})
    CategoriesDF[['Transaction', 'Category']] = CategoriesDF['Transaction - Category'].str.split(' - ', expand=True)

    return CategoriesDF

In [15]:
#test the categorise_transactions function
CatTrans = categorise_transactions('Best Baking Syndey Metro, oil paint canvas , uberdrive int aiport, utility Sept',llm)
CatTrans

,Transaction - Category,Transaction,Category
0,1. Best Baking Syndey Metro - food,1. Best Baking Syndey Metro,food
1,2. Oil paint canvas - creative,2. Oil paint canvas,creative
2,3. Uber drive Int Airport - transport,3. Uber drive Int Airport,transport
3,4. Utility Sept - utility,4. Utility Sept,utility

In [16]:
def process_categories(UniqueTransactions, IndexTransList, llm):
  
    #initialise a new empty dataframe
    CategoriesDF = pd.DataFrame()
    #set a max tries if LLM output incorrect format. Rule set '-' between transaction and category
    MaxTries = 5

    #loop through the unique transactions and get the block of categories using index list built before
    for i in range(0,len(IndexTransList)-1):
        #extract transaction belong to current block
        BlockTrans= UniqueTransactions[IndexTransList[i]:IndexTransList[i+1]]
        #Separate each transaction with a comma before fit them to LLM
        BlockTrans = ', '.join(BlockTrans)
        # retry loop when LLM return output of incorrect format
        for j in range(MaxTries):
            try:
                #call llm to classify the block of transactions
                Categories = categorise_transactions(BlockTrans, llm)
                #Append the output to the dataframe.
                CategoriesDF = pd.concat([CategoriesDF, Categories], ignore_index=True)                                 
            except:
                if j < MaxTries:
                    continue
                else:
                    raise Exception (f"Failed to categorise transactions after {MaxTries} attempts.")
            break
    return CategoriesDF
#process all uniques categories
CategoriesDF = process_categories(UniqueTransactions, IndexTransList, llm)
CategoriesDF

,Transaction - Category,Transaction,Category
0,1. Baci Pasta Cafe - Food,1. Baci Pasta Cafe,Food
1,2. Kmart - Shopping,2. Kmart,Shopping
2,3. Barwon Water - Utilities,3. Barwon Water,Utilities
3,4. Tong Li Supermarkets - Groceries,4. Tong Li Supermarkets,Groceries
4,5. Agodacom Aluna Hotel - Accommodation,5. Agodacom Aluna Hotel,Accommodation
5,6. Aust Hlth Mgmt Grp Pl - Unknown,6. Aust Hlth Mgmt Grp Pl,Unknown
6,7. Opal Topup - Transport,7. Opal Topup,Transport
7,8. Transfer From Cba - Unknown,8. Transfer From Cba,Unknown
8,9. Aldi Stores - Groceries,9. Aldi Stores,Groceries
9,10. Transfer From Metro Art Galary - Unknown,10. Transfer From Metro Art Galary,Unknown
10,1. Best Baking Sydney Metro - Food,1. Best Baking Sydney Metro,Food
11,2. Oil paint canvas - Creative,2. Oil paint canvas,Creative
12,3. Uber drive to airport - Transport,3. Uber drive to airport,Transport
13,4. Utility Sept - Utility,4. Utility Sept,Utility
14,5. Big Apple - Food,5. Big Apple,Food
15,6. Woolworths Great Western - Grocery,6. Woolworths Great Western,Grocery
16,7. Coles - Grocery,7. Coles,Grocery
17,8. Virgin - Entertainment,8. Virgin,Entertainment
18,9. Payment To Occomtyltd Internet - Service,9. Payment To Occomtyltd Internet,Service
19,10. Payment To Credit Card - Financial Services,10. Payment To Credit Card,Financial Services
20,11. Sushi Hub - Food,11. Sushi Hub,Food
21,12. Payment From Cba - Financial Services,12. Payment From Cba,Financial Services
22,13. Aaa Artcraft - Creative,13. Aaa Artcraft,Creative
23,14. Woolworths Strathfield Pl Strathfield - Grocery,14. Woolworths Strathfield Pl Strathfield,Grocery
24,1. Best Baking Sydney Metro - food,1. Best Baking Sydney Metro,food
25,2. Oil paint canvas - creative,2. Oil paint canvas,creative
26,3. Uber drive to airport - transport,3. Uber drive to airport,transport
27,4. Utility Sept - utility,4. Utility Sept,utility
28,5. Aldimobile - transport,5. Aldimobile,transport
29,6. Target - shopping,6. Target,shopping
30,7. Uber Trip Sydney - transport,7. Uber Trip Sydney,transport
31,8. Westfield - shopping,8. Westfield,shopping
32,9. Velocity Freq Flyer - travel,9. Velocity Freq Flyer,travel
33,10. Ezymart Central Stn - shopping,10. Ezymart Central Stn,shopping
34,11. Yarravalleywater Yvow - utility,11. Yarravalleywater Yvow,utility
35,12. Daiso - shopping,12. Daiso,shopping
36,13. Reversal of account fees - miscellaneous,13. Reversal of account fees,miscellaneous
37,14. Transport for NSW Opal - transport,14. Transport for NSW Opal,transport
38,1. Best Baking Sydney Metro - Food,1. Best Baking Sydney Metro,Food
39,2. Oil paint canvas - Creative,2. Oil paint canvas,Creative
40,3. Uber drive to airport - Transport,3. Uber drive to airport,Transport
41,4. Utility Sept - Utility,4. Utility Sept,Utility
42,5. Ikea - Home Improvement,5. Ikea,Home Improvement
43,6. Just Ripe Northland - Groceries,6. Just Ripe Northland,Groceries
44,7. Body Sculpting Clinic - Health & Wellness,7. Body Sculpting Clinic,Health & Wellness
45,8. Roof Shining - Home Maintenance,8. Roof Shining,Home Maintenance
46,9. Virgin Australia - Travel,9. Virgin Australia,Travel
47,10. Uniqlo - Clothing,10. Uniqlo,Clothing
48,11. Banking Service Fees - Financial Services,11. Banking Service Fees,Financial Services
49,12. Red Energy - Utilities,12. Red Energy,Utilities
50,13. Purchase Totalav - Personal Care,13. Purchase Totalav,Personal Care
51,14. Account Servicing Fee - Financial Services,14. Account Servicing Fee,Financial Services

In [17]:
#remove unwanted characters leading each transaction
CategoriesDF['Transaction'] = CategoriesDF['Transaction'].str.replace(r'^(\d+\.|\*)\s+', '', regex=True).str.strip()
CategoriesDF['Category']=CategoriesDF['Category'].str.title()
CategoriesDF

,Transaction - Category,Transaction,Category
0,1. Baci Pasta Cafe - Food,Baci Pasta Cafe,Food
1,2. Kmart - Shopping,Kmart,Shopping
2,3. Barwon Water - Utilities,Barwon Water,Utilities
3,4. Tong Li Supermarkets - Groceries,Tong Li Supermarkets,Groceries
4,5. Agodacom Aluna Hotel - Accommodation,Agodacom Aluna Hotel,Accommodation
5,6. Aust Hlth Mgmt Grp Pl - Unknown,Aust Hlth Mgmt Grp Pl,Unknown
6,7. Opal Topup - Transport,Opal Topup,Transport
7,8. Transfer From Cba - Unknown,Transfer From Cba,Unknown
8,9. Aldi Stores - Groceries,Aldi Stores,Groceries
9,10. Transfer From Metro Art Galary - Unknown,Transfer From Metro Art Galary,Unknown
10,1. Best Baking Sydney Metro - Food,Best Baking Sydney Metro,Food
11,2. Oil paint canvas - Creative,Oil paint canvas,Creative
12,3. Uber drive to airport - Transport,Uber drive to airport,Transport
13,4. Utility Sept - Utility,Utility Sept,Utility
14,5. Big Apple - Food,Big Apple,Food
15,6. Woolworths Great Western - Grocery,Woolworths Great Western,Grocery
16,7. Coles - Grocery,Coles,Grocery
17,8. Virgin - Entertainment,Virgin,Entertainment
18,9. Payment To Occomtyltd Internet - Service,Payment To Occomtyltd Internet,Service
19,10. Payment To Credit Card - Financial Services,Payment To Credit Card,Financial Services
20,11. Sushi Hub - Food,Sushi Hub,Food
21,12. Payment From Cba - Financial Services,Payment From Cba,Financial Services
22,13. Aaa Artcraft - Creative,Aaa Artcraft,Creative
23,14. Woolworths Strathfield Pl Strathfield - Grocery,Woolworths Strathfield Pl Strathfield,Grocery
24,1. Best Baking Sydney Metro - food,Best Baking Sydney Metro,Food
25,2. Oil paint canvas - creative,Oil paint canvas,Creative
26,3. Uber drive to airport - transport,Uber drive to airport,Transport
27,4. Utility Sept - utility,Utility Sept,Utility
28,5. Aldimobile - transport,Aldimobile,Transport
29,6. Target - shopping,Target,Shopping
30,7. Uber Trip Sydney - transport,Uber Trip Sydney,Transport
31,8. Westfield - shopping,Westfield,Shopping
32,9. Velocity Freq Flyer - travel,Velocity Freq Flyer,Travel
33,10. Ezymart Central Stn - shopping,Ezymart Central Stn,Shopping
34,11. Yarravalleywater Yvow - utility,Yarravalleywater Yvow,Utility
35,12. Daiso - shopping,Daiso,Shopping
36,13. Reversal of account fees - miscellaneous,Reversal of account fees,Miscellaneous
37,14. Transport for NSW Opal - transport,Transport for NSW Opal,Transport
38,1. Best Baking Sydney Metro - Food,Best Baking Sydney Metro,Food
39,2. Oil paint canvas - Creative,Oil paint canvas,Creative
40,3. Uber drive to airport - Transport,Uber drive to airport,Transport
41,4. Utility Sept - Utility,Utility Sept,Utility
42,5. Ikea - Home Improvement,Ikea,Home Improvement
43,6. Just Ripe Northland - Groceries,Just Ripe Northland,Groceries
44,7. Body Sculpting Clinic - Health & Wellness,Body Sculpting Clinic,Health & Wellness
45,8. Roof Shining - Home Maintenance,Roof Shining,Home Maintenance
46,9. Virgin Australia - Travel,Virgin Australia,Travel
47,10. Uniqlo - Clothing,Uniqlo,Clothing
48,11. Banking Service Fees - Financial Services,Banking Service Fees,Financial Services
49,12. Red Energy - Utilities,Red Energy,Utilities
50,13. Purchase Totalav - Personal Care,Purchase Totalav,Personal Care
51,14. Account Servicing Fee - Financial Services,Account Servicing Fee,Financial Services

In [18]:
SourceDF=TransformedDF
SourceDF = SourceDF.rename(columns={"Transaction": "SrcTransaction"})
CategorisedTrans = pd.merge(
    SourceDF, CategoriesDF, left_on="SrcTransaction", right_on="Transaction", how="left"
)
CategorisedTrans

,Date,Amount,SrcTransaction,Income/Expense,Transaction - Category,Transaction,Category
0,30/07/2025,-4,Baci Pasta Cafe,Expense,1. Baci Pasta Cafe - Food,Baci Pasta Cafe,Food
1,30/12/2025,-9,Kmart,Expense,2. Kmart - Shopping,Kmart,Shopping
2,07/01/2026,-197,Barwon Water,Expense,3. Barwon Water - Utilities,Barwon Water,Utilities
3,15/01/2025,-62,Tong Li Supermarkets,Expense,4. Tong Li Supermarkets - Groceries,Tong Li Supermarkets,Groceries
4,12/11/2025,-3895,Agodacom Aluna Hotel,Expense,5. Agodacom Aluna Hotel - Accommodation,Agodacom Aluna Hotel,Accommodation
...,...,...,...,...,...,...,...
93,19/01/2026,-16,Woolworthsgreat Western,Expense,NaN,NaN,NaN
94,25/05/2026,-19,Woolworthswestfield Camp,Expense,NaN,NaN,NaN
95,18/11/2025,-992,Paid To Credit Card,Expense,NaN,NaN,NaN
96,11/11/2024,167,Sold Osis Painting,Income,NaN,NaN,NaN
97,04/04/2025,-121,Origin Energy,Expense,NaN,NaN,NaN

In [19]:
CategorisedTrans = CategorisedTrans.dropna()
CategorisedTrans

,Date,Amount,SrcTransaction,Income/Expense,Transaction - Category,Transaction,Category
0,30/07/2025,-4,Baci Pasta Cafe,Expense,1. Baci Pasta Cafe - Food,Baci Pasta Cafe,Food
1,30/12/2025,-9,Kmart,Expense,2. Kmart - Shopping,Kmart,Shopping
2,07/01/2026,-197,Barwon Water,Expense,3. Barwon Water - Utilities,Barwon Water,Utilities
3,15/01/2025,-62,Tong Li Supermarkets,Expense,4. Tong Li Supermarkets - Groceries,Tong Li Supermarkets,Groceries
4,12/11/2025,-3895,Agodacom Aluna Hotel,Expense,5. Agodacom Aluna Hotel - Accommodation,Agodacom Aluna Hotel,Accommodation
5,02/08/2024,-170,Aust Hlth Mgmt Grp Pl,Expense,6. Aust Hlth Mgmt Grp Pl - Unknown,Aust Hlth Mgmt Grp Pl,Unknown
6,08/07/2025,-24,Opal Topup,Expense,7. Opal Topup - Transport,Opal Topup,Transport
7,07/10/2024,5073,Transfer From Cba,Income,8. Transfer From Cba - Unknown,Transfer From Cba,Unknown
8,21/01/2026,-23,Aldi Stores,Expense,9. Aldi Stores - Groceries,Aldi Stores,Groceries
9,19/06/2026,2000,Transfer From Metro Art Galary,Income,10. Transfer From Metro Art Galary - Unknown,Transfer From Metro Art Galary,Unknown
10,13/01/2025,-30,Big Apple,Expense,5. Big Apple - Food,Big Apple,Food
12,18/05/2026,-1,Coles,Expense,7. Coles - Grocery,Coles,Grocery
13,22/07/2024,-1500,Virgin,Expense,8. Virgin - Entertainment,Virgin,Entertainment
14,19/01/2026,550,Transfer From Cba,Income,8. Transfer From Cba - Unknown,Transfer From Cba,Unknown
16,17/07/2024,-313,Payment To Credit Card,Expense,10. Payment To Credit Card - Financial Services,Payment To Credit Card,Financial Services
17,24/12/2025,-11,Sushi Hub,Expense,11. Sushi Hub - Food,Sushi Hub,Food
18,07/04/2026,1375,Payment From Cba,Income,12. Payment From Cba - Financial Services,Payment From Cba,Financial Services
19,08/07/2025,-24,Coles,Expense,7. Coles - Grocery,Coles,Grocery
20,22/09/2025,-946,Aaa Artcraft,Expense,13. Aaa Artcraft - Creative,Aaa Artcraft,Creative
26,19/08/2025,-7,Tong Li Supermarkets,Expense,4. Tong Li Supermarkets - Groceries,Tong Li Supermarkets,Groceries
27,02/10/2025,-197,Barwon Water,Expense,3. Barwon Water - Utilities,Barwon Water,Utilities
29,23/12/2025,-133,Tong Li Supermarkets,Expense,4. Tong Li Supermarkets - Groceries,Tong Li Supermarkets,Groceries
35,11/11/2024,-39,Kmart,Expense,2. Kmart - Shopping,Kmart,Shopping
37,01/12/2025,-33,Aldimobile,Expense,5. Aldimobile - transport,Aldimobile,Transport
38,20/04/2026,-100,Target,Expense,6. Target - shopping,Target,Shopping
39,07/01/2025,-11,Uber Trip Sydney,Expense,7. Uber Trip Sydney - transport,Uber Trip Sydney,Transport
41,12/06/2025,-188,Westfield,Expense,8. Westfield - shopping,Westfield,Shopping
42,20/10/2025,-35,Velocity Freq Flyer,Expense,9. Velocity Freq Flyer - travel,Velocity Freq Flyer,Travel
43,28/10/2024,4778,Transfer From Cba,Income,8. Transfer From Cba - Unknown,Transfer From Cba,Unknown
44,04/10/2024,-70,Aust Hlth Mgmt Grp Pl,Expense,6. Aust Hlth Mgmt Grp Pl - Unknown,Aust Hlth Mgmt Grp Pl,Unknown
45,10/12/2025,-2,Ezymart Central Stn,Expense,10. Ezymart Central Stn - shopping,Ezymart Central Stn,Shopping
46,22/10/2025,-8,Tong Li Supermarkets,Expense,4. Tong Li Supermarkets - Groceries,Tong Li Supermarkets,Groceries
47,27/03/2025,-288,Yarravalleywater Yvow,Expense,11. Yarravalleywater Yvow - utility,Yarravalleywater Yvow,Utility
48,30/06/2026,-22,Daiso,Expense,12. Daiso - shopping,Daiso,Shopping
49,02/06/2025,2375,Transfer From Cba,Income,8. Transfer From Cba - Unknown,Transfer From Cba,Unknown
50,13/04/2026,-517,Payment To Credit Card,Expense,10. Payment To Credit Card - Financial Services,Payment To Credit Card,Financial Services
57,12/06/2025,-20,Tong Li Supermarkets,Expense,4. Tong Li Supermarkets - Groceries,Tong Li Supermarkets,Groceries
58,17/12/2024,-422,Payment To Credit Card,Expense,10. Payment To Credit Card - Financial Services,Payment To Credit Card,Financial Services
63,27/08/2025,-8,Aldi Stores,Expense,9. Aldi Stores - Groceries,Aldi Stores,Groceries
66,11/06/2025,-40,Target,Expense,6. Target - shopping,Target,Shopping
67,01/07/2025,-20,Kmart,Expense,2. Kmart - Shopping,Kmart,Shopping
69,17/04/2025,-1000,Ikea,Expense,5. Ikea - Home Improvement,Ikea,Home Improvement
70,22/04/2026,-17,Just Ripe Northland,Expense,6. Just Ripe Northland - Groceries,Just Ripe Northland,Groceries
71,14/07/2025,-303,Body Sculpting Clinic,Expense,7. Body Sculpting Clinic - Health & Wellness,Body Sculpting Clinic,Health & Wellness
72,14/07/2025,-1500,Roof Shining,Expense,8. Roof Shining - Home Maintenance,Roof Shining,Home Maintenance
74,01/10/2024,-16,Uber Trip Sydney,Expense,7. Uber Trip Sydney - transport,Uber Trip Sydney,Transport
76,03/03/2026,-7,Coles,Expense,7. Coles - Grocery,Coles,Grocery
77,18/11/2024,-14,Uniqlo,Expense,10. Uniqlo - Clothing,Uniqlo,Clothing
78,24/02/2025,-3,Banking Service Fees,Expense,11. Banking Service Fees - Financial Services,Banking Service Fees,Financial Services
79,16/08/2024,-399,Red Energy,Expense,12. Red Energy - Utilities,Red Energy,Utilities
80,07/10/2024,-31,Purchase Totalav,Expense,13. Purchase Totalav - Personal Care,Purchase Totalav,Personal Care
81,26/11/2025,-39,Aldi Stores,Expense,9. Aldi Stores - Groceries,Aldi Stores,Groceries
83,31/07/2024,-5,Account Servicing Fee,Expense,14. Account Servicing Fee - Financial Services,Account Servicing Fee,Financial Services
84,24/02/2026,-30,Tong Li Supermarkets,Expense,4. Tong Li Supermarkets - Groceries,Tong Li Supermarkets,Groceries
85,21/01/2026,-114,Tong Li Supermarkets,Expense,4. Tong Li Supermarkets - Groceries,Tong Li Supermarkets,Groceries
88,31/03/2025,2375,Transfer From Cba,Income,8. Transfer From Cba - Unknown,Transfer From Cba,Unknown
89,30/09/2024,-5,Account Servicing Fee,Expense,14. Account Servicing Fee - Financial Services,Account Servicing Fee,Financial Services
90,08/12/2025,-2,Ezymart Central Stn,Expense,10. Ezymart Central Stn - shopping,Ezymart Central Stn,Shopping
91,15/05/2025,-37,Aldi Stores,Expense,9. Aldi Stores - Groceries,Aldi Stores,Groceries
92,23/07/2025,-137,Aldi Stores,Expense,9. Aldi Stores - Groceries,Aldi Stores,Groceries

In [21]:
UniqCategories = CategorisedTrans['Category'].unique()
UniqCategories

<StringArray>
[              'Food',           'Shopping',          'Utilities',
          'Groceries',      'Accommodation',            'Unknown',
          'Transport',            'Grocery',      'Entertainment',
 'Financial Services',           'Creative',             'Travel',
            'Utility',   'Home Improvement',  'Health & Wellness',
   'Home Maintenance',           'Clothing',      'Personal Care']
Length: 18, dtype: str

In [22]:
def regroup_category():
    # 2. Define a lookup dictionary
    LookupDic = {
        "Food": "Dining & Leisure",
        "Entertainment": "Dining & Leisure",
        "Groceries": "Supplies & Essentials",
        "Grocery": "Supplies & Essentials",
        "Shopping": "Shopping & Retails",
        "Clothing": "Shopping & Retails",
        "Home": "Shopping & Retails",
        "Utilities": "Utility"
    }
    CategorisedTrans['RefineCategory'] = CategorisedTrans['Category'].map(LookupDic).fillna(CategorisedTrans['Category'])
    return CategorisedTrans

CategorisedTrans = regroup_category()
print(CategorisedTrans[['Category', 'RefineCategory']])

              Category         RefineCategory
0                 Food       Dining & Leisure
1             Shopping     Shopping & Retails
2            Utilities                Utility
3            Groceries  Supplies & Essentials
4        Accommodation          Accommodation
5              Unknown                Unknown
6            Transport              Transport
7              Unknown                Unknown
8            Groceries  Supplies & Essentials
9              Unknown                Unknown
10                Food       Dining & Leisure
12             Grocery  Supplies & Essentials
13       Entertainment       Dining & Leisure
14             Unknown                Unknown
16  Financial Services     Financial Services
17                Food       Dining & Leisure
18  Financial Services     Financial Services
19             Grocery  Supplies & Essentials
20            Creative               Creative
26           Groceries  Supplies & Essentials
27           Utilities                Utility
29           Groceries  Supplies & Essentials
35            Shopping     Shopping & Retails
37           Transport              Transport
38            Shopping     Shopping & Retails
39           Transport              Transport
41            Shopping     Shopping & Retails
42              Travel                 Travel
43             Unknown                Unknown
44             Unknown                Unknown
45            Shopping     Shopping & Retails
46           Groceries  Supplies & Essentials
47             Utility                Utility
48            Shopping     Shopping & Retails
49             Unknown                Unknown
50  Financial Services     Financial Services
57           Groceries  Supplies & Essentials
58  Financial Services     Financial Services
63           Groceries  Supplies & Essentials
66            Shopping     Shopping & Retails
67            Shopping     Shopping & Retails
69    Home Improvement       Home Improvement
70           Groceries  Supplies & Essentials
71   Health & Wellness      Health & Wellness
72    Home Maintenance       Home Maintenance
74           Transport              Transport
76             Grocery  Supplies & Essentials
77            Clothing     Shopping & Retails
78  Financial Services     Financial Services
79           Utilities                Utility
80       Personal Care          Personal Care
81           Groceries  Supplies & Essentials
83  Financial Services     Financial Services
84           Groceries  Supplies & Essentials
85           Groceries  Supplies & Essentials
88             Unknown                Unknown
89  Financial Services     Financial Services
90            Shopping     Shopping & Retails
91           Groceries  Supplies & Essentials
92           Groceries  Supplies & Essentials

In [23]:
CategorisedTrans=CategorisedTrans.drop(columns = 'Category').rename(columns ={'RefineCategory': 'Category'})
CategorisedTrans

,Date,Amount,SrcTransaction,Income/Expense,Transaction - Category,Transaction,Category
0,30/07/2025,-4,Baci Pasta Cafe,Expense,1. Baci Pasta Cafe - Food,Baci Pasta Cafe,Dining & Leisure
1,30/12/2025,-9,Kmart,Expense,2. Kmart - Shopping,Kmart,Shopping & Retails
2,07/01/2026,-197,Barwon Water,Expense,3. Barwon Water - Utilities,Barwon Water,Utility
3,15/01/2025,-62,Tong Li Supermarkets,Expense,4. Tong Li Supermarkets - Groceries,Tong Li Supermarkets,Supplies & Essentials
4,12/11/2025,-3895,Agodacom Aluna Hotel,Expense,5. Agodacom Aluna Hotel - Accommodation,Agodacom Aluna Hotel,Accommodation
5,02/08/2024,-170,Aust Hlth Mgmt Grp Pl,Expense,6. Aust Hlth Mgmt Grp Pl - Unknown,Aust Hlth Mgmt Grp Pl,Unknown
6,08/07/2025,-24,Opal Topup,Expense,7. Opal Topup - Transport,Opal Topup,Transport
7,07/10/2024,5073,Transfer From Cba,Income,8. Transfer From Cba - Unknown,Transfer From Cba,Unknown
8,21/01/2026,-23,Aldi Stores,Expense,9. Aldi Stores - Groceries,Aldi Stores,Supplies & Essentials
9,19/06/2026,2000,Transfer From Metro Art Galary,Income,10. Transfer From Metro Art Galary - Unknown,Transfer From Metro Art Galary,Unknown
10,13/01/2025,-30,Big Apple,Expense,5. Big Apple - Food,Big Apple,Dining & Leisure
12,18/05/2026,-1,Coles,Expense,7. Coles - Grocery,Coles,Supplies & Essentials
13,22/07/2024,-1500,Virgin,Expense,8. Virgin - Entertainment,Virgin,Dining & Leisure
14,19/01/2026,550,Transfer From Cba,Income,8. Transfer From Cba - Unknown,Transfer From Cba,Unknown
16,17/07/2024,-313,Payment To Credit Card,Expense,10. Payment To Credit Card - Financial Services,Payment To Credit Card,Financial Services
17,24/12/2025,-11,Sushi Hub,Expense,11. Sushi Hub - Food,Sushi Hub,Dining & Leisure
18,07/04/2026,1375,Payment From Cba,Income,12. Payment From Cba - Financial Services,Payment From Cba,Financial Services
19,08/07/2025,-24,Coles,Expense,7. Coles - Grocery,Coles,Supplies & Essentials
20,22/09/2025,-946,Aaa Artcraft,Expense,13. Aaa Artcraft - Creative,Aaa Artcraft,Creative
26,19/08/2025,-7,Tong Li Supermarkets,Expense,4. Tong Li Supermarkets - Groceries,Tong Li Supermarkets,Supplies & Essentials
27,02/10/2025,-197,Barwon Water,Expense,3. Barwon Water - Utilities,Barwon Water,Utility
29,23/12/2025,-133,Tong Li Supermarkets,Expense,4. Tong Li Supermarkets - Groceries,Tong Li Supermarkets,Supplies & Essentials
35,11/11/2024,-39,Kmart,Expense,2. Kmart - Shopping,Kmart,Shopping & Retails
37,01/12/2025,-33,Aldimobile,Expense,5. Aldimobile - transport,Aldimobile,Transport
38,20/04/2026,-100,Target,Expense,6. Target - shopping,Target,Shopping & Retails
39,07/01/2025,-11,Uber Trip Sydney,Expense,7. Uber Trip Sydney - transport,Uber Trip Sydney,Transport
41,12/06/2025,-188,Westfield,Expense,8. Westfield - shopping,Westfield,Shopping & Retails
42,20/10/2025,-35,Velocity Freq Flyer,Expense,9. Velocity Freq Flyer - travel,Velocity Freq Flyer,Travel
43,28/10/2024,4778,Transfer From Cba,Income,8. Transfer From Cba - Unknown,Transfer From Cba,Unknown
44,04/10/2024,-70,Aust Hlth Mgmt Grp Pl,Expense,6. Aust Hlth Mgmt Grp Pl - Unknown,Aust Hlth Mgmt Grp Pl,Unknown
45,10/12/2025,-2,Ezymart Central Stn,Expense,10. Ezymart Central Stn - shopping,Ezymart Central Stn,Shopping & Retails
46,22/10/2025,-8,Tong Li Supermarkets,Expense,4. Tong Li Supermarkets - Groceries,Tong Li Supermarkets,Supplies & Essentials
47,27/03/2025,-288,Yarravalleywater Yvow,Expense,11. Yarravalleywater Yvow - utility,Yarravalleywater Yvow,Utility
48,30/06/2026,-22,Daiso,Expense,12. Daiso - shopping,Daiso,Shopping & Retails
49,02/06/2025,2375,Transfer From Cba,Income,8. Transfer From Cba - Unknown,Transfer From Cba,Unknown
50,13/04/2026,-517,Payment To Credit Card,Expense,10. Payment To Credit Card - Financial Services,Payment To Credit Card,Financial Services
57,12/06/2025,-20,Tong Li Supermarkets,Expense,4. Tong Li Supermarkets - Groceries,Tong Li Supermarkets,Supplies & Essentials
58,17/12/2024,-422,Payment To Credit Card,Expense,10. Payment To Credit Card - Financial Services,Payment To Credit Card,Financial Services
63,27/08/2025,-8,Aldi Stores,Expense,9. Aldi Stores - Groceries,Aldi Stores,Supplies & Essentials
66,11/06/2025,-40,Target,Expense,6. Target - shopping,Target,Shopping & Retails
67,01/07/2025,-20,Kmart,Expense,2. Kmart - Shopping,Kmart,Shopping & Retails
69,17/04/2025,-1000,Ikea,Expense,5. Ikea - Home Improvement,Ikea,Home Improvement
70,22/04/2026,-17,Just Ripe Northland,Expense,6. Just Ripe Northland - Groceries,Just Ripe Northland,Supplies & Essentials
71,14/07/2025,-303,Body Sculpting Clinic,Expense,7. Body Sculpting Clinic - Health & Wellness,Body Sculpting Clinic,Health & Wellness
72,14/07/2025,-1500,Roof Shining,Expense,8. Roof Shining - Home Maintenance,Roof Shining,Home Maintenance
74,01/10/2024,-16,Uber Trip Sydney,Expense,7. Uber Trip Sydney - transport,Uber Trip Sydney,Transport
76,03/03/2026,-7,Coles,Expense,7. Coles - Grocery,Coles,Supplies & Essentials
77,18/11/2024,-14,Uniqlo,Expense,10. Uniqlo - Clothing,Uniqlo,Shopping & Retails
78,24/02/2025,-3,Banking Service Fees,Expense,11. Banking Service Fees - Financial Services,Banking Service Fees,Financial Services
79,16/08/2024,-399,Red Energy,Expense,12. Red Energy - Utilities,Red Energy,Utility
80,07/10/2024,-31,Purchase Totalav,Expense,13. Purchase Totalav - Personal Care,Purchase Totalav,Personal Care
81,26/11/2025,-39,Aldi Stores,Expense,9. Aldi Stores - Groceries,Aldi Stores,Supplies & Essentials
83,31/07/2024,-5,Account Servicing Fee,Expense,14. Account Servicing Fee - Financial Services,Account Servicing Fee,Financial Services
84,24/02/2026,-30,Tong Li Supermarkets,Expense,4. Tong Li Supermarkets - Groceries,Tong Li Supermarkets,Supplies & Essentials
85,21/01/2026,-114,Tong Li Supermarkets,Expense,4. Tong Li Supermarkets - Groceries,Tong Li Supermarkets,Supplies & Essentials
88,31/03/2025,2375,Transfer From Cba,Income,8. Transfer From Cba - Unknown,Transfer From Cba,Unknown
89,30/09/2024,-5,Account Servicing Fee,Expense,14. Account Servicing Fee - Financial Services,Account Servicing Fee,Financial Services
90,08/12/2025,-2,Ezymart Central Stn,Expense,10. Ezymart Central Stn - shopping,Ezymart Central Stn,Shopping & Retails
91,15/05/2025,-37,Aldi Stores,Expense,9. Aldi Stores - Groceries,Aldi Stores,Supplies & Essentials
92,23/07/2025,-137,Aldi Stores,Expense,9. Aldi Stores - Groceries,Aldi Stores,Supplies & Essentials

In [39]:
CategorisedTrans.to_csv('Categorised_cleaned_trans.csv')