In [1]:
from langchain_ollama import OllamaLLM
import pandas as pd
import numpy as np
import re
from cleantext import clean

In [2]:
llm = OllamaLLM(model="financial_analyser_llama2:latest")
llm.invoke("Who is leading using AI to fight financial crime?")

"\nAs a financial assistant, I can tell you that several organizations and institutions are leveraging artificial intelligence (AI) to combat financial crime. Here are some examples:\n\n1. Financial Institutions: Banks, insurance companies, and other financial institutions are using AI-powered tools to detect and prevent money laundering, terrorist financing, and other financial crimes. These tools can analyze large amounts of data to identify patterns and anomalies that may indicate illegal activity.\n2. Government Agencies: Law enforcement agencies and regulatory bodies are also using AI to combat financial crime. For example, the US Department of Justice's Computer Crimes Unit has used AI-powered tools to investigate and prosecute cybercrime cases involving fraud and identity theft.\n3. Fintech Companies: Financial technology companies (fintech) are also using AI to combat financial crime. For example, fraud detection startup, Feedzai, uses AI to analyze transaction data and identify potential fraud patterns.\n4. Non-Profit Organizations: Some non-profit organizations, such as the Financial Integrity Network (FIN), are using AI to combat financial crime. FIN's platform uses machine learning algorithms to analyze data from various sources, including financial transactions and social media, to identify potential money laundering and terrorist financing activities.\n5. International Organizations: International organizations such as the United Nations Office on Drugs and Crime (UNODC) are also using AI to combat financial crime. UNODC's Anti-Money Laundering/Combating the Financing of Terrorism (AML/CFT) program uses AI-powered tools to analyze data from multiple sources, including financial transactions and law enforcement reports, to identify potential money laundering and terrorist financing activities.\n\nSome examples of companies using AI in financial crime fighting include:\n\n1. Accenture: Accenture's Financial Crime Management solution uses AI-powered tools to detect and prevent financial crimes such as fraud, money laundering, and terrorist financing.\n2. IBM: IBM's Watson for Regulatory Compliance platform uses AI-powered algorithms to analyze large amounts of data to identify potential risks and improve compliance with regulations related to financial crime.\n3. SAS Institute: SAS Institute's Fraud Detection and Prevention solution uses machine learning algorithms to detect and prevent fraudulent activity in various industries, including finance.\n4. Palantir Technologies: Palantir Technologies' Gotham platform uses AI-powered tools to analyze large amounts of data to identify potential risks and improve compliance with regulations related to financial crime.\n\nThese are just a few examples of organizations using AI to combat financial crime. As the use of AI in this space continues to grow, we can expect even more innovative solutions to emerge in the future."

In [3]:
def read_data():
    TransDF = pd.read_csv('sample.csv')
    TransDF['Amount'] = pd.to_numeric(TransDF['Amount'], errors='coerce').fillna(0).astype(int)    
    return TransDF

TransformedDF = read_data()

#make sure the data has the right data type
print(TransformedDF.dtypes)

Date        str
Amount    int64
Desc        str
dtype: object

In [5]:
TransformedDF.head()

         Date  Amount                                  Desc
0  27/03/2025    -288            YARRAVALLEYWATER YVOW
1  11/06/2025     -40                       TARGET 5144
2  05/09/2024      -3  EFTPOS PAYPAL *      SYDNEY       AU
3  02/10/2025    -197                          BARWON WATER
4  22/07/2024   -1500                             VIRGIN AU

In [6]:
def normalise_transaction(value):
    if pd.isna(value):
        return ""
    value = str(value).strip().lower()
    value = re.sub(r"[^a-z]+", " ", value)
    return re.sub(r"\s+", " ", value).strip()

#make a copy of transformed source to new df

TransformedDF["Transaction"] = TransformedDF["Desc"].apply(normalise_transaction)

TransformedDF.drop(columns = ["Desc"], inplace = True)

TransformedDF

          Date  Amount                Transaction
0   27/03/2025    -288      yarravalleywater yvow
1   11/06/2025     -40                     target
2   05/09/2024      -3    eftpos paypal sydney au
3   02/10/2025    -197               barwon water
4   22/07/2024   -1500                  virgin au
5   27/01/2026     -21   woolworths great western
6   15/01/2025     -62       tong li supermarkets
7   19/06/2026    2000      from metro art galary
8   11/11/2024     167       yellow bird painting
9   01/12/2025     -33                aldi mobile
10  04/11/2024    2067    transfer from macquarie
11  17/12/2024    -422     payment to credit card
12  22/04/2024     -17        just ripe northland
13  25/05/2026     -19  woolworths westfield camp
14  27/08/2025      -8                aldi stores
15  14/07/2025    -303      body sculpting clinic
16  24/12/2024     -51                  sushi hub
17  29/05/2026       5   reversal of account fees
18  14/05/2025    -202          les family clinic
19  06/01/2025   -2816             payment to fmc
20  30/12/2025      -5       sumbul meats poultry
21  04/10/2024     -70     aust hlth mgmt grp p l
22  07/10/2024    5073     transfer from anz bank
23  18/05/2026      -1                      coles
24  20/10/2025     -35         velocity australia
25  30/06/2026     -22                      daiso
26  08/12/2025      -2        ezymart central stn
27  12/11/2025   -3895      agoda com aluna hotel
28  22/10/2025      -5   woolworths great western
29  23/07/2024    -137                aldi stores
30  25/11/2025     -21        soul origins mascot
31  31/03/2025    2375          transfer from cba
32  21/01/2026    -114       tong li supermarkets
33  01/10/2024     -16           uber trip sydney
34  09/02/2026     -17        yummy saigon summer
35  03/03/2026      -7                      coles
36  18/11/2025    -992        paid to credit card

In [7]:
UniqueTransactions=TransformedDF['Transaction'].unique()
len(UniqueTransactions)
UniqueTransactions

<StringArray>
[    'yarravalleywater yvow',                    'target',
   'eftpos paypal sydney au',              'barwon water',
                 'virgin au',  'woolworths great western',
      'tong li supermarkets',     'from metro art galary',
      'yellow bird painting',               'aldi mobile',
   'transfer from macquarie',    'payment to credit card',
       'just ripe northland', 'woolworths westfield camp',
               'aldi stores',     'body sculpting clinic',
                 'sushi hub',  'reversal of account fees',
         'les family clinic',            'payment to fmc',
      'sumbul meats poultry',    'aust hlth mgmt grp p l',
    'transfer from anz bank',                     'coles',
        'velocity australia',                     'daiso',
       'ezymart central stn',     'agoda com aluna hotel',
       'soul origins mascot',         'transfer from cba',
          'uber trip sydney',       'yummy saigon summer',
       'paid to credit card']
Length: 33, dtype: str

In [8]:
response = llm.invoke('can you add a proper category to the following items. Do not apply reasonong. ' \
'Responde with category. For example: Coles Express Bread - groceries, Big Apple transaction - groceries' + 
', '.join(UniqueTransactions[1:10]))
response = response.split('\n')
response

['',
 'Sure! Here are the categories I would assign to each of the items you listed:',
 '',
 '1. Coles Express Bread - Groceries',
 '2. Big Apple transaction - Groceries',
 '3. Eftpos PayPal Sydney Au - Groceries',
 '4. Barwon Water - Utilities',
 '5. Virgin Au - Telecommunications',
 '6. Woolworths Great Western - Groceries',
 '7. Tong Li Supermarkets - Groceries',
 '8. From Metro Art Gallery - Entertainment',
 '9. Yellow Bird Painting - Entertainment',
 '10. Aldi Mobile - Electronics']

In [9]:
# Generate an arrary of sequence of 10s and append the final boundary index
IndexTransList = (
    np.append(np.arange(0, len(UniqueTransactions), 10), 
              len(UniqueTransactions)).tolist()
)

IndexTransList

[0, 10, 20, 30, 33]

In [10]:
# Validate response 's format
from pydantic import BaseModel, field_validator
from typing import List

class ResponseChecks(BaseModel):
    data: List[str]
    @field_validator('data')
    def check_length(cls, value):
        for item in value:
            if len(item) >0:
                assert "-" in item, f"Item '{item}' does not contain a hyphen"
#Pass asertion
ResponseChecks(data=['Hello World - greeting', 'banana cake - fruit'])

ResponseChecks(data=None)

In [12]:
#fail assertion
ResponseChecks(data=['Hello-World', 'banana fruit'])

ValidationError: 1 validation error for ResponseChecks
data
  Assertion failed, Item 'banana fruit' does not contain a hyphen [type=assertion_error, input_value=['Hello-World', 'banana fruit'], input_type=list]
    For further information visit https://errors.pydantic.dev/2.13/v/assertion_error

In [13]:
def categorise_transactions(transactions, llm):
    response = llm.invoke("Can you add an appropriate category to the following expenses. For example: " \
    "Best Baking Syndey Metro - food, oil paint canvas - creative, uberdrive int aiport - transport, utility Sept - utility. " \
    "Categories should be less than 4 characters. " + transactions)
    response = response.split('\n')
    
    #removing the explaination lines at the beginning and end of the response
    TransIndexes = [index for index in range(len(response)) if response[index] == '']
    if len(TransIndexes) == 1:
        response = response[(TransIndexes[0] + 1):]
    else:
        response = response[(TransIndexes[0] + 1) : TransIndexes[1]]

    #validate response for '-' to separate transaction and category
    ResponseChecks(data = response)
    
    # assigned the response to a dataframe
    CategoriesDF = pd.DataFrame({'Transaction - Category': response})
    CategoriesDF[['Transaction', 'Category']] = CategoriesDF['Transaction - Category'].str.split(' - ', expand=True)

    return CategoriesDF

In [15]:
#test the categorise_transactions function
TestTrans = categorise_transactions('Best Baking Syndey Metro, oil paint canvas , uberdrive int aiport, utility Sept',llm)
TestTrans

                Transaction - Category                 Transaction   Category
0    * Best Baking Syndey Metro - food  * Best Baking Syndey Metro       food
1        * Oil paint canvas - creative          * Oil paint canvas   creative
2  * Uber drive to airport - transport     * Uber drive to airport  transport
3             * Utility Sept - utility              * Utility Sept    utility

In [16]:
def process_categories(UniqueTransactions, IndexTransList, llm):
  
    #initialise a new empty dataframe
    CategoriesDF = pd.DataFrame()
    #set a max tries if LLM output incorrect format. Rule set '-' between transaction and category
    MaxTries = 5

    #loop through the unique transactions and get the block of categories using index list built before
    for i in range(0,len(IndexTransList)-1):
        #extract transaction belong to current block
        BlockTrans= UniqueTransactions[IndexTransList[i]:IndexTransList[i+1]]
        #Separate each transaction with a comma before fit them to LLM
        BlockTrans = ', '.join(BlockTrans)
        # retry loop when LLM return output of incorrect format
        for j in range(MaxTries):
            try:
                #call llm to classify the block of transactions
                Categories = categorise_transactions(BlockTrans, llm)
                #Append the output to the dataframe.
                CategoriesDF = pd.concat([CategoriesDF, Categories], ignore_index=True)                                 
            except:
                if j < MaxTries:
                    continue
                else:
                    raise Exception (f"Failed to categorise transactions after {MaxTries} attempts.")
            break
    return CategoriesDF
#process all uniques categories
CategoriesDF = process_categories(UniqueTransactions, IndexTransList, llm)
CategoriesDF

,Transaction - Category,Transaction,Category
0,* Best Baking Sydney Metro - food,* Best Baking Sydney Metro,food
1,* Oil paint canvas - creative,* Oil paint canvas,creative
2,* Uber drive to airport - transport,* Uber drive to airport,transport
3,* Utility Sept - utility,* Utility Sept,utility
4,* Yarravalleywater yvow - utility,* Yarravalleywater yvow,utility
5,* Target - shopping,* Target,shopping
6,* Eftpos paypal Sydney au - payment,* Eftpos paypal Sydney au,payment
7,* Barwon water - utility,* Barwon water,utility
8,* Virgin au - communication,* Virgin au,communication
9,* Woolworths great western - groceries,* Woolworths great western,groceries
10,* Tong li supermarkets - groceries,* Tong li supermarkets,groceries
11,* From metro art gallery - entertainment,* From metro art gallery,entertainment
12,* Yellow bird painting - creative,* Yellow bird painting,creative
13,* Aldi mobile - communication,* Aldi mobile,communication
14,1. Best Baking Sydney Metro - Food,1. Best Baking Sydney Metro,Food
15,2. Oil paint canvas - Creative,2. Oil paint canvas,Creative
16,3. Uber drive to airport - Transport,3. Uber drive to airport,Transport
17,4. Utility Sept - Utility,4. Utility Sept,Utility
18,5. Transfer from Macquarie - Finance,5. Transfer from Macquarie,Finance
19,6. Payment to credit card - Finance,6. Payment to credit card,Finance
20,7. Just Ripe Northland - Groceries,7. Just Ripe Northland,Groceries
21,8. Woolworths Westfield Camp - Groceries,8. Woolworths Westfield Camp,Groceries
22,9. Aldi Stores - Groceries,9. Aldi Stores,Groceries
23,10. Body Sculpting Clinic - Health & Wellness,10. Body Sculpting Clinic,Health & Wellness
24,11. Sushi Hub - Dining,11. Sushi Hub,Dining
25,12. Reversal of account fees - Miscellaneous,12. Reversal of account fees,Miscellaneous
26,13. Les Family Clinic - Health & Wellness,13. Les Family Clinic,Health & Wellness
27,14. Payment to FMC - Finance,14. Payment to FMC,Finance
28,1. Best Baking Sydney Metro - Food,1. Best Baking Sydney Metro,Food
29,2. Oil paint canvas - Creative,2. Oil paint canvas,Creative
30,3. Uber drive to airport - Transport,3. Uber drive to airport,Transport
31,4. Utility Sept - Utility,4. Utility Sept,Utility
32,5. Subbul Meats Poultry - Food,5. Subbul Meats Poultry,Food
33,6. Aust Hlth Mgmt Grp P L - Insurance,6. Aust Hlth Mgmt Grp P L,Insurance
34,7. Transfer from ANZ Bank - Financial Services,7. Transfer from ANZ Bank,Financial Services
35,8. Coles - Grocery,8. Coles,Grocery
36,9. Velocity Australia - Travel,9. Velocity Australia,Travel
37,10. Daiso - Home Goods,10. Daiso,Home Goods
38,11. Ezymart Central Stn - Shopping,11. Ezymart Central Stn,Shopping
39,12. Agoda com Aluna Hotel - Travel,12. Agoda com Aluna Hotel,Travel
40,13. Soul Origins Mascot - Marketing,13. Soul Origins Mascot,Marketing
41,14. Transfer from CBA - Financial Services,14. Transfer from CBA,Financial Services
42,* Uber trip Sydney - Transport,* Uber trip Sydney,Transport
43,* Yummy Saigon Summer - Food,* Yummy Saigon Summer,Food
44,* Paid to Credit Card - Financial Services,* Paid to Credit Card,Financial Services

In [18]:
#remove unwanted characters leading each transaction
CategoriesDF['Transaction'] = CategoriesDF['Transaction'].str.replace(r'^(\d+\.|\*)\s+', '', regex=True).str.strip()
CategoriesDF['Category']=CategoriesDF['Category'].str.title()
CategoriesDF

,Transaction - Category,Transaction,Category
0,* Best Baking Sydney Metro - food,Best Baking Sydney Metro,Food
1,* Oil paint canvas - creative,Oil paint canvas,Creative
2,* Uber drive to airport - transport,Uber drive to airport,Transport
3,* Utility Sept - utility,Utility Sept,Utility
4,* Yarravalleywater yvow - utility,Yarravalleywater yvow,Utility
5,* Target - shopping,Target,Shopping
6,* Eftpos paypal Sydney au - payment,Eftpos paypal Sydney au,Payment
7,* Barwon water - utility,Barwon water,Utility
8,* Virgin au - communication,Virgin au,Communication
9,* Woolworths great western - groceries,Woolworths great western,Groceries
10,* Tong li supermarkets - groceries,Tong li supermarkets,Groceries
11,* From metro art gallery - entertainment,From metro art gallery,Entertainment
12,* Yellow bird painting - creative,Yellow bird painting,Creative
13,* Aldi mobile - communication,Aldi mobile,Communication
14,1. Best Baking Sydney Metro - Food,Best Baking Sydney Metro,Food
15,2. Oil paint canvas - Creative,Oil paint canvas,Creative
16,3. Uber drive to airport - Transport,Uber drive to airport,Transport
17,4. Utility Sept - Utility,Utility Sept,Utility
18,5. Transfer from Macquarie - Finance,Transfer from Macquarie,Finance
19,6. Payment to credit card - Finance,Payment to credit card,Finance
20,7. Just Ripe Northland - Groceries,Just Ripe Northland,Groceries
21,8. Woolworths Westfield Camp - Groceries,Woolworths Westfield Camp,Groceries
22,9. Aldi Stores - Groceries,Aldi Stores,Groceries
23,10. Body Sculpting Clinic - Health & Wellness,Body Sculpting Clinic,Health & Wellness
24,11. Sushi Hub - Dining,Sushi Hub,Dining
25,12. Reversal of account fees - Miscellaneous,Reversal of account fees,Miscellaneous
26,13. Les Family Clinic - Health & Wellness,Les Family Clinic,Health & Wellness
27,14. Payment to FMC - Finance,Payment to FMC,Finance
28,1. Best Baking Sydney Metro - Food,Best Baking Sydney Metro,Food
29,2. Oil paint canvas - Creative,Oil paint canvas,Creative
30,3. Uber drive to airport - Transport,Uber drive to airport,Transport
31,4. Utility Sept - Utility,Utility Sept,Utility
32,5. Subbul Meats Poultry - Food,Subbul Meats Poultry,Food
33,6. Aust Hlth Mgmt Grp P L - Insurance,Aust Hlth Mgmt Grp P L,Insurance
34,7. Transfer from ANZ Bank - Financial Services,Transfer from ANZ Bank,Financial Services
35,8. Coles - Grocery,Coles,Grocery
36,9. Velocity Australia - Travel,Velocity Australia,Travel
37,10. Daiso - Home Goods,Daiso,Home Goods
38,11. Ezymart Central Stn - Shopping,Ezymart Central Stn,Shopping
39,12. Agoda com Aluna Hotel - Travel,Agoda com Aluna Hotel,Travel
40,13. Soul Origins Mascot - Marketing,Soul Origins Mascot,Marketing
41,14. Transfer from CBA - Financial Services,Transfer from CBA,Financial Services
42,* Uber trip Sydney - Transport,Uber trip Sydney,Transport
43,* Yummy Saigon Summer - Food,Yummy Saigon Summer,Food
44,* Paid to Credit Card - Financial Services,Paid to Credit Card,Financial Services

In [19]:
DupTransDF = CategoriesDF[CategoriesDF.duplicated(subset=['Transaction'], keep=False)]
DupTransDF

                  Transaction - Category               Transaction   Category
0      * Best Baking Sydney Metro - food  Best Baking Sydney Metro       Food
1          * Oil paint canvas - creative          Oil paint canvas   Creative
2    * Uber drive to airport - transport     Uber drive to airport  Transport
3               * Utility Sept - utility              Utility Sept    Utility
14    1. Best Baking Sydney Metro - Food  Best Baking Sydney Metro       Food
15        2. Oil paint canvas - Creative          Oil paint canvas   Creative
16  3. Uber drive to airport - Transport     Uber drive to airport  Transport
17             4. Utility Sept - Utility              Utility Sept    Utility
28    1. Best Baking Sydney Metro - Food  Best Baking Sydney Metro       Food
29        2. Oil paint canvas - Creative          Oil paint canvas   Creative
30  3. Uber drive to airport - Transport     Uber drive to airport  Transport
31             4. Utility Sept - Utility              Utility Sept    Utility

In [20]:
#merge model output, no text cleaning, to the source data
SourceDF = TransformedDF.copy()
SourceDF['Transaction']=SourceDF['Transaction'].str.title()
TestMergeDFs = pd.merge(
    SourceDF,
    CategoriesDF[["Transaction", "Category"]],
    on="Transaction",
    how="left"
)
TestMergeDFs

          Date  Amount                Transaction           Category
0   27/03/2025    -288      Yarravalleywater Yvow                NaN
1   11/06/2025     -40                     Target           Shopping
2   05/09/2024      -3    Eftpos Paypal Sydney Au                NaN
3   02/10/2025    -197               Barwon Water                NaN
4   22/07/2024   -1500                  Virgin Au                NaN
5   27/01/2026     -21   Woolworths Great Western                NaN
6   15/01/2025     -62       Tong Li Supermarkets                NaN
7   19/06/2026    2000      From Metro Art Galary                NaN
8   11/11/2024     167       Yellow Bird Painting                NaN
9   01/12/2025     -33                Aldi Mobile                NaN
10  04/11/2024    2067    Transfer From Macquarie                NaN
11  17/12/2024    -422     Payment To Credit Card                NaN
12  22/04/2024     -17        Just Ripe Northland          Groceries
13  25/05/2026     -19  Woolworths Westfield Camp          Groceries
14  27/08/2025      -8                Aldi Stores          Groceries
15  14/07/2025    -303      Body Sculpting Clinic  Health & Wellness
16  24/12/2024     -51                  Sushi Hub             Dining
17  29/05/2026       5   Reversal Of Account Fees                NaN
18  14/05/2025    -202          Les Family Clinic  Health & Wellness
19  06/01/2025   -2816             Payment To Fmc                NaN
20  30/12/2025      -5       Sumbul Meats Poultry                NaN
21  04/10/2024     -70     Aust Hlth Mgmt Grp P L          Insurance
22  07/10/2024    5073     Transfer From Anz Bank                NaN
23  18/05/2026      -1                      Coles            Grocery
24  20/10/2025     -35         Velocity Australia             Travel
25  30/06/2026     -22                      Daiso         Home Goods
26  08/12/2025      -2        Ezymart Central Stn           Shopping
27  12/11/2025   -3895      Agoda Com Aluna Hotel                NaN
28  22/10/2025      -5   Woolworths Great Western                NaN
29  23/07/2024    -137                Aldi Stores          Groceries
30  25/11/2025     -21        Soul Origins Mascot          Marketing
31  31/03/2025    2375          Transfer From Cba                NaN
32  21/01/2026    -114       Tong Li Supermarkets                NaN
33  01/10/2024     -16           Uber Trip Sydney                NaN
34  09/02/2026     -17        Yummy Saigon Summer               Food
35  03/03/2026      -7                      Coles            Grocery
36  18/11/2025    -992        Paid To Credit Card                NaN

In [21]:
# def normalise_transaction(value):
#     if pd.isna(value):
#         return ""
#     value = str(value).strip().lower()
#     value = re.sub(r"[^a-z0-9]+", " ", value)
#     return re.sub(r"\s+", " ", value).strip()

#make a copy of transformed source to new df
# SourceDF = TransformedDF.copy()
# SourceDF = SourceDF.rename(columns={"Transaction": "SrcTransaction"})

CategoriesDF = CategoriesDF.copy()
CategoriesDF["Transaction"] = CategoriesDF["Transaction"].fillna("").astype(str).str.strip()
CategoriesDF["Transaction"] = CategoriesDF["Transaction"].str.replace(r"^(\d+\.|\*)\s+", "", 
regex=True)
CategoriesDF["JoinKey"] = CategoriesDF["Transaction"].apply(normalise_transaction)
CategoriesDF = CategoriesDF.drop_duplicates(subset=["JoinKey"], keep="first")

TransformedDF["JoinKey"] = TransformedDF["Transaction"].apply(normalise_transaction)

CategorisedTrans = pd.merge(
    TransformedDF,
    CategoriesDF[["JoinKey", "Category"]],
    on="JoinKey",
    how="left"
).drop(columns=["JoinKey"])

CategorisedTrans["Category"] = CategorisedTrans["Category"].fillna("Uncategorised")
CategorisedTrans

          Date  Amount                Transaction            Category
0   27/03/2025    -288      yarravalleywater yvow             Utility
1   11/06/2025     -40                     target            Shopping
2   05/09/2024      -3    eftpos paypal sydney au             Payment
3   02/10/2025    -197               barwon water             Utility
4   22/07/2024   -1500                  virgin au       Communication
5   27/01/2026     -21   woolworths great western           Groceries
6   15/01/2025     -62       tong li supermarkets           Groceries
7   19/06/2026    2000      from metro art galary       Uncategorised
8   11/11/2024     167       yellow bird painting            Creative
9   01/12/2025     -33                aldi mobile       Communication
10  04/11/2024    2067    transfer from macquarie             Finance
11  17/12/2024    -422     payment to credit card             Finance
12  22/04/2024     -17        just ripe northland           Groceries
13  25/05/2026     -19  woolworths westfield camp           Groceries
14  27/08/2025      -8                aldi stores           Groceries
15  14/07/2025    -303      body sculpting clinic   Health & Wellness
16  24/12/2024     -51                  sushi hub              Dining
17  29/05/2026       5   reversal of account fees       Miscellaneous
18  14/05/2025    -202          les family clinic   Health & Wellness
19  06/01/2025   -2816             payment to fmc             Finance
20  30/12/2025      -5       sumbul meats poultry       Uncategorised
21  04/10/2024     -70     aust hlth mgmt grp p l           Insurance
22  07/10/2024    5073     transfer from anz bank  Financial Services
23  18/05/2026      -1                      coles             Grocery
24  20/10/2025     -35         velocity australia              Travel
25  30/06/2026     -22                      daiso          Home Goods
26  08/12/2025      -2        ezymart central stn            Shopping
27  12/11/2025   -3895      agoda com aluna hotel              Travel
28  22/10/2025      -5   woolworths great western           Groceries
29  23/07/2024    -137                aldi stores           Groceries
30  25/11/2025     -21        soul origins mascot           Marketing
31  31/03/2025    2375          transfer from cba  Financial Services
32  21/01/2026    -114       tong li supermarkets           Groceries
33  01/10/2024     -16           uber trip sydney           Transport
34  09/02/2026     -17        yummy saigon summer                Food
35  03/03/2026      -7                      coles             Grocery
36  18/11/2025    -992        paid to credit card  Financial Services

In [42]:
CategorisedTrans = CategorisedTrans.dropna()
CategorisedTrans

,Date,Amount,SrcTransaction,Income/Expense,Category
0,27/03/2025,-288,Yarravalleywater Yvow,Expense,Utility
1,11/06/2025,-40,Target,Expense,Shopping
2,05/09/2024,-3,Eftpos Paypal Sydney Au,Expense,Online Spending
3,02/10/2025,-197,Barwon Water,Expense,Utility
4,22/07/2024,-1500,Virgin,Expense,Transport
6,15/01/2025,-62,Tong Li Supermarkets,Expense,Groceries
8,11/11/2024,167,Yellow Bird Painting,Income,Creative
9,01/12/2025,-33,Aldi Mobile,Expense,Online Spending
10,04/11/2024,2067,Transfer From Macquarie,Income,Transfer
11,17/12/2024,-422,Payment To Credit Card,Expense,Payment
12,22/04/2024,-17,Just Ripe Northland,Expense,Grocery
14,27/08/2025,-8,Aldi Stores,Expense,Grocery
15,14/07/2025,-303,Body Sculpting Clinic,Expense,Health
16,24/12/2024,-51,Sushi Hub,Expense,Dining
17,29/05/2026,5,Reversal Of Account Fees,Income,Misc
18,14/05/2025,-202,Les Family Clinic,Expense,Health
19,06/01/2025,-2816,Payment To Fmc,Expense,Payment
20,30/12/2025,-5,Sumbul Meats Poultry,Expense,Groceries
21,04/10/2024,-70,Aust Hlth Mgmt Grp Pl,Expense,Misc
25,30/06/2026,-22,Daiso,Expense,Shopping
26,08/12/2025,-2,Ezymart Central Stn,Expense,Shopping
27,12/11/2025,-3895,Agodacom Aluna Hotel,Expense,Travel
29,23/07/2024,-137,Aldi Stores,Expense,Grocery
30,25/11/2025,-21,Soul Origins Mascot,Expense,Misc
32,21/01/2026,-114,Tong Li Supermarkets,Expense,Groceries
33,01/10/2024,-16,Uber Trip Sydney,Expense,Transport

In [22]:
UniqCategories = CategorisedTrans['Category'].unique()
UniqCategories

<StringArray>
[           'Utility',           'Shopping',            'Payment',
      'Communication',          'Groceries',      'Uncategorised',
           'Creative',            'Finance',  'Health & Wellness',
             'Dining',      'Miscellaneous',          'Insurance',
 'Financial Services',            'Grocery',             'Travel',
         'Home Goods',          'Marketing',          'Transport',
               'Food']
Length: 19, dtype: str

In [28]:
def regroup_category():
    # 2. Define a lookup dictionary
    LookupDic = {
        "Food": "Dining & Leisure",
        "Entertainment": "Dining & Leisure",
        "Groceries": "Supplies & Essentials",
        "Grocery": "Supplies & Essentials",
        "Shopping": "Shopping & Retails",
        "Clothing": "Shopping & Retails",
        "Home": "Shopping & Retails",
        "Utilities": "Utility"
    }
    CategorisedTrans['CategoryCalss'] = CategorisedTrans['Category'].map(LookupDic).fillna(CategorisedTrans['Category'])
    return CategorisedTrans

CategorisedTrans = regroup_category()
CategorisedTrans

,Date,Amount,Transaction,Category,CategoryCalss
0,27/03/2025,-288,yarravalleywater yvow,Utility,Utility
1,11/06/2025,-40,target,Shopping,Shopping & Retails
2,05/09/2024,-3,eftpos paypal sydney au,Payment,Payment
3,02/10/2025,-197,barwon water,Utility,Utility
4,22/07/2024,-1500,virgin au,Communication,Communication
5,27/01/2026,-21,woolworths great western,Groceries,Supplies & Essentials
6,15/01/2025,-62,tong li supermarkets,Groceries,Supplies & Essentials
7,19/06/2026,2000,from metro art galary,Uncategorised,Uncategorised
8,11/11/2024,167,yellow bird painting,Creative,Creative
9,01/12/2025,-33,aldi mobile,Communication,Communication
10,04/11/2024,2067,transfer from macquarie,Finance,Finance
11,17/12/2024,-422,payment to credit card,Finance,Finance
12,22/04/2024,-17,just ripe northland,Groceries,Supplies & Essentials
13,25/05/2026,-19,woolworths westfield camp,Groceries,Supplies & Essentials
14,27/08/2025,-8,aldi stores,Groceries,Supplies & Essentials
15,14/07/2025,-303,body sculpting clinic,Health & Wellness,Health & Wellness
16,24/12/2024,-51,sushi hub,Dining,Dining
17,29/05/2026,5,reversal of account fees,Miscellaneous,Miscellaneous
18,14/05/2025,-202,les family clinic,Health & Wellness,Health & Wellness
19,06/01/2025,-2816,payment to fmc,Finance,Finance
20,30/12/2025,-5,sumbul meats poultry,Uncategorised,Uncategorised
21,04/10/2024,-70,aust hlth mgmt grp p l,Insurance,Insurance
22,07/10/2024,5073,transfer from anz bank,Financial Services,Financial Services
23,18/05/2026,-1,coles,Grocery,Supplies & Essentials
24,20/10/2025,-35,velocity australia,Travel,Travel
25,30/06/2026,-22,daiso,Home Goods,Home Goods
26,08/12/2025,-2,ezymart central stn,Shopping,Shopping & Retails
27,12/11/2025,-3895,agoda com aluna hotel,Travel,Travel
28,22/10/2025,-5,woolworths great western,Groceries,Supplies & Essentials
29,23/07/2024,-137,aldi stores,Groceries,Supplies & Essentials
30,25/11/2025,-21,soul origins mascot,Marketing,Marketing
31,31/03/2025,2375,transfer from cba,Financial Services,Financial Services
32,21/01/2026,-114,tong li supermarkets,Groceries,Supplies & Essentials
33,01/10/2024,-16,uber trip sydney,Transport,Transport
34,09/02/2026,-17,yummy saigon summer,Food,Dining & Leisure
35,03/03/2026,-7,coles,Grocery,Supplies & Essentials
36,18/11/2025,-992,paid to credit card,Financial Services,Financial Services