In [2]:
from langchain_ollama import OllamaLLM
import pandas as pd
import numpy as np
import re
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)

In [3]:
llm = OllamaLLM(model="Milo")
llm.invoke("Who leads in AI-powered financial crime solutions in Australia")

'\nOh, boy! *excitedly* Well, let me tell you, mate! In Australia, there are a few players that lead the way in AI-powered financial crime solutions! *leaning in*\n\nFirst off, there\'s our very own AI-powered transaction classification system, FinCrimeAI. It\'s a real doozy, let me tell you! *chuckles* This thing can classify transactions in no time, and it\'s so accurate, it\'s like having an extra set of eyes on the job! *nods*\n\nBut wait, there\'s more! *excitedly* Our friends over at ANZ Bank have developed this snazzy AI-powered system called "Smart Fraud Detection." It\'s a real brainiac, if I do say so myself! *winks* This thing can detect fraud in real-time, and it\'s got a clever way of learning from past transactions to improve its accuracy over time. It\'s like having a superhero on your banking team! *admiringly*\n\nAnd last but not least, there\'s the Westpac Group\'s "Adaptive AI" system. *in awe* This thing is a real marvel! *excitedly* It uses machine learning to detect and prevent fraud in a way that\'s tailored to each individual customer. That means it can learn from your specific banking habits and patterns, so it can identify potential threats before they even happen! *incredulous*\n\nSo there you have it, mate! These are the leaders in AI-powered financial crime solutions in Australia. *grinning* And with systems like these, you can rest assured that your banking transactions are safe and secure! *smiling* Now, if you\'ll excuse me, I have some more FinCrimeAI system to classify! *excitedly*'

In [5]:
def read_data():
    TransDF = pd.read_csv('sample.csv')
    TransDF['Amount'] = pd.to_numeric(TransDF['Amount'], errors='coerce').fillna(0).astype(int)    
    return TransDF

TransformedDF = read_data()

#make sure the data has the right data type
print(TransformedDF.dtypes)

Date        str
Amount    int64
Desc        str
dtype: object

In [6]:
TransformedDF.head()

         Date  Amount                        Desc
0  27/03/2025    -288  YARRAVALLEYWATER YVOW
1  11/06/2025     -40   TARGET WESTFIELD 5144
2  02/10/2025    -197                BARWON WATER
3  22/07/2024   -1500             VIRGIN AIRLINES
4  27/01/2026     -21  WOOLWORTHS/GREAT WESTERN

In [ ]:
def normalise_transaction(value):
    if pd.isna(value):
        return ""
    value = str(value).strip().lower()
    value = re.sub(r"[^a-z]+", " ", value)
    return re.sub(r"\s+", " ", value).strip()

TransformedDF["Transaction"] = TransformedDF["Desc"].apply(normalise_transaction)
TransformedDF["Transaction"] = TransformedDF["Transaction"].str.title()

TransformedDF.drop(columns = ["Desc"], inplace = True)

TransformedDF

          Date  Amount                         Transaction
0   27/03/2025    -288               Yarravalleywater Yvow
1   11/06/2025     -40                    Target Westfield
2   02/10/2025    -197                        Barwon Water
3   22/07/2024   -1500                     Virgin Airlines
4   27/01/2026     -21            Woolworths Great Western
5   15/01/2025     -62                         Service Nsw
6   19/06/2026    6372               From Metro Art Galary
7   11/11/2024     167                Yellow Bird Painting
8   01/12/2025     -33                         Aldi Mobile
9   04/11/2024    2067  Transfer From Macquarie University
10  17/12/2024    -422                       Fund Transfer
11  22/04/2024     -17                 Just Ripe Northland
12  25/05/2026     -19           Woolworths Westfield Camp
13  27/08/2025      -8                         Aldi Stores
14  14/07/2025    -303               Body Sculpting Clinic
15  24/12/2024     -51                           Sushi Hub
16  14/05/2025    -202                   Les Family Clinic
17  06/01/2025   -2816                      Payment To Fmc
18  30/12/2025      -5                Sumbul Meats Poultry
19  04/10/2024     -70              Aust Hlth Mgmt Grp P L
20  07/10/2024    5073              Transfer From Anz Bank
21  18/05/2026      -1                               Coles
22  20/10/2025     -35                  Velocity Australia
23  30/06/2026     -22                     Daiso Westfield
24  08/12/2025      -2                     Ezymart Central
25  12/11/2025   -3895               Agoda Com Aluna Hotel
26  22/10/2025      -5            Woolworths Great Western
27  23/07/2024    -137                         Aldi Stores
28  21/01/2026    -114         Chemist Warehouse Westfield
29  01/10/2024     -16                    Uber Trip Sydney
30  09/02/2026     -17                 Yummy Saigon Summer
31  03/03/2026      -7                               Coles
32  18/11/2025    -992                       Fund Transfer

In [8]:
UniqueTransactions = TransformedDF['Transaction'].unique()
len(UniqueTransactions)
UniqueTransactions

<StringArray>
[             'Yarravalleywater Yvow',                   'Target Westfield',
                       'Barwon Water',                    'Virgin Airlines',
           'Woolworths Great Western',                        'Service Nsw',
              'From Metro Art Galary',               'Yellow Bird Painting',
                        'Aldi Mobile', 'Transfer From Macquarie University',
                      'Fund Transfer',                'Just Ripe Northland',
          'Woolworths Westfield Camp',                        'Aldi Stores',
              'Body Sculpting Clinic',                          'Sushi Hub',
                  'Les Family Clinic',                     'Payment To Fmc',
               'Sumbul Meats Poultry',             'Aust Hlth Mgmt Grp P L',
             'Transfer From Anz Bank',                              'Coles',
                 'Velocity Australia',                    'Daiso Westfield',
                    'Ezymart Central',              'Agoda Com Aluna Hotel',
        'Chemist Warehouse Westfield',                   'Uber Trip Sydney',
                'Yummy Saigon Summer']
Length: 29, dtype: str

In [9]:
response = llm.invoke('can you add a proper category to the following items. Do not apply reasonong. ' \
'Responde with category. For example: Coles Express Bread - groceries, Big Apple transaction - groceries' + 
', '.join(UniqueTransactions[1:10]))
response = response.split('\n')
response

['',
 'Sure! Here are the categories for each of the items you provided:',
 '',
 '1. Coles Express Bread - Groceries',
 '2. Big Apple transaction - Groceries',
 '3. Barwon Water - Utilities',
 '4. Virgin Airlines - Travel',
 '5. Woolworths Great Western - Groceries',
 '6. Service NSW - Government',
 '7. From Metro Art Gallery - Arts & Entertainment',
 '8. Yellow Bird Painting - Arts & Entertainment',
 '9. Aldi Mobile - Retail',
 '10. Transfer From Macquarie University - Education']

In [10]:
# Generate an arrary of sequence of 10s and append the final boundary index
IndexTransList = (
    np.append(np.arange(0, len(UniqueTransactions), 10), 
              len(UniqueTransactions)).tolist()
)

IndexTransList

[0, 10, 20, 29]

In [11]:
# Validate response 's format
from pydantic import BaseModel, field_validator
from typing import List

class ResponseChecks(BaseModel):
    data: List[str]
    @field_validator('data')
    def check_length(cls, value):
        for item in value:
            if len(item) >0:
                assert "-" in item, f"Item '{item}' does not contain a hyphen"
#Pass asertion
ResponseChecks(data=['Hello World - greeting', 'banana cake - fruit'])

ResponseChecks(data=None)

In [22]:
#fail assertion
ResponseChecks(data=['Hello-World', 'banana fruit'])

ValidationError: 1 validation error for ResponseChecks
data
  Assertion failed, Item 'banana fruit' does not contain a hyphen [type=assertion_error, input_value=['Hello-World', 'banana fruit'], input_type=list]
    For further information visit https://errors.pydantic.dev/2.13/v/assertion_error

In [12]:
def categorise_transactions(transactions, llm):
    response = llm.invoke("Can you add an appropriate category to the following expenses. For example: " \
    "Best Baking Syndey Metro - food, oil paint canvas - creative, uberdrive int aiport - transport, utility Sept - utility. " \
    "Categories should be less than 4 characters. " + transactions)
    response = response.split('\n')
    
    #removing the explaination lines at the beginning and end of the response
    TransIndexes = [index for index in range(len(response)) if response[index] == '']
    if len(TransIndexes) == 1:
        response = response[(TransIndexes[0] + 1):]
    else:
        response = response[(TransIndexes[0] + 1) : TransIndexes[1]]

    #validate response for '-' to separate transaction and category
    ResponseChecks(data = response)
    
    # assigned the response to a dataframe
    CategoriesDF = pd.DataFrame({'Transaction - Category': response})
    CategoriesDF[['Transaction', 'Category']] = CategoriesDF['Transaction - Category'].str.split(' - ', expand=True)

    return CategoriesDF

In [15]:
#test the categorise_transactions function
TestTrans = categorise_transactions('Best Baking Syndey Metro, oil paint canvas , uberdrive int aiport, utility Sept',llm)
TestTrans

,Transaction - Category,Transaction,Category
0,1. Best Baking Sydney Metro - food,1. Best Baking Sydney Metro,food
1,2. Oil paint canvas - creative,2. Oil paint canvas,creative
2,3. Uber drive to airport - transport,3. Uber drive to airport,transport
3,4. Utility Sept - utility,4. Utility Sept,utility

In [18]:
def process_categories(UniqueTransactions, IndexTransList, llm):
  
    #initialise a new empty dataframe
    CategoriesDF = pd.DataFrame()
    #set a max tries if LLM output incorrect format. Rule set '-' between transaction and category
    MaxTries = 5

    #loop through the unique transactions and get the block of categories using index list built before
    for i in range(0,len(IndexTransList)-1):
        #extract transaction belong to current block
        BlockTrans= UniqueTransactions[IndexTransList[i]:IndexTransList[i+1]]
        #Separate each transaction with a comma before fit them to LLM
        BlockTrans = ', '.join(BlockTrans)
        # retry loop when LLM return output of incorrect format
        for j in range(MaxTries):
            try:
                #call llm to classify the block of transactions
                Categories = categorise_transactions(BlockTrans, llm)
                #Append the output to the dataframe.
                CategoriesDF = pd.concat([CategoriesDF, Categories], ignore_index=True)                                 
            except:
                if j < MaxTries:
                    continue
                else:
                    raise Exception (f"Failed to categorise transactions after {MaxTries} attempts.")
            break
    return CategoriesDF
#process all uniques categories
CategoriesDF = process_categories(UniqueTransactions, IndexTransList, llm)
CategoriesDF

,Transaction - Category,Transaction,Category
0,1. Yarravalleywater Yvow - Utility,1. Yarravalleywater Yvow,Utility
1,2. Target Westfield - Shopping,2. Target Westfield,Shopping
2,3. Barwon Water - Utility,3. Barwon Water,Utility
3,4. Virgin Airlines - Transport,4. Virgin Airlines,Transport
4,5. Woolworths Great Western - Grocery,5. Woolworths Great Western,Grocery
5,6. Service NSW - Government,6. Service NSW,Government
6,7. From Metro Art Galary - Entertainment,7. From Metro Art Galary,Entertainment
7,8. Yellow Bird Painting - Creative,8. Yellow Bird Painting,Creative
8,9. Aldi Mobile - Shopping,9. Aldi Mobile,Shopping
9,10. Transfer From Macquarie University - Education,10. Transfer From Macquarie University,Education
10,* Best Baking Sydney Metro - food,* Best Baking Sydney Metro,food
11,* Oil paint canvas - creative,* Oil paint canvas,creative
12,* Uber drive to airport - transport,* Uber drive to airport,transport
13,* Utility Sept - utility,* Utility Sept,utility
14,* Fund Transfer - finance,* Fund Transfer,finance
15,* Just Ripe Northland - food,* Just Ripe Northland,food
16,* Woolworths Westfield Camp - grocery,* Woolworths Westfield Camp,grocery
17,* Aldi Stores - grocery,* Aldi Stores,grocery
18,* Body Sculpting Clinic - health & wellness,* Body Sculpting Clinic,health & wellness
19,* Sushi Hub - dining,* Sushi Hub,dining
20,* Les Family Clinic - health & wellness,* Les Family Clinic,health & wellness
21,* Payment To Fmc - miscellaneous,* Payment To Fmc,miscellaneous
22,* Sumbul Meats Poultry - food,* Sumbul Meats Poultry,food
23,* Aust Hlth Mgmt Grp P L - miscellaneous,* Aust Hlth Mgmt Grp P L,miscellaneous
24,1. Transfer From Anz Bank - Utility,1. Transfer From Anz Bank,Utility
25,2. Coles - Groceries,2. Coles,Groceries
26,3. Velocity Australia - Travel,3. Velocity Australia,Travel
27,4. Daiso Westfield - Shopping,4. Daiso Westfield,Shopping
28,5. Ezymart Central - Groceries,5. Ezymart Central,Groceries
29,6. Agoda Com Aluna Hotel - Travel,6. Agoda Com Aluna Hotel,Travel
30,7. Chemist Warehouse Westfield - Health,7. Chemist Warehouse Westfield,Health
31,8. Uber Trip Sydney - Transport,8. Uber Trip Sydney,Transport
32,9. Yummy Saigon Summer - Food,9. Yummy Saigon Summer,Food

In [19]:
#remove unwanted characters leading each transaction
CategoriesDF['Transaction'] = CategoriesDF['Transaction'].str.replace(r'^(\d+\.|\*)\s+', '', regex=True).str.strip()
CategoriesDF['Category']=CategoriesDF['Category'].str.title()
CategoriesDF

,Transaction - Category,Transaction,Category
0,1. Yarravalleywater Yvow - Utility,Yarravalleywater Yvow,Utility
1,2. Target Westfield - Shopping,Target Westfield,Shopping
2,3. Barwon Water - Utility,Barwon Water,Utility
3,4. Virgin Airlines - Transport,Virgin Airlines,Transport
4,5. Woolworths Great Western - Grocery,Woolworths Great Western,Grocery
5,6. Service NSW - Government,Service NSW,Government
6,7. From Metro Art Galary - Entertainment,From Metro Art Galary,Entertainment
7,8. Yellow Bird Painting - Creative,Yellow Bird Painting,Creative
8,9. Aldi Mobile - Shopping,Aldi Mobile,Shopping
9,10. Transfer From Macquarie University - Education,Transfer From Macquarie University,Education
10,* Best Baking Sydney Metro - food,Best Baking Sydney Metro,Food
11,* Oil paint canvas - creative,Oil paint canvas,Creative
12,* Uber drive to airport - transport,Uber drive to airport,Transport
13,* Utility Sept - utility,Utility Sept,Utility
14,* Fund Transfer - finance,Fund Transfer,Finance
15,* Just Ripe Northland - food,Just Ripe Northland,Food
16,* Woolworths Westfield Camp - grocery,Woolworths Westfield Camp,Grocery
17,* Aldi Stores - grocery,Aldi Stores,Grocery
18,* Body Sculpting Clinic - health & wellness,Body Sculpting Clinic,Health & Wellness
19,* Sushi Hub - dining,Sushi Hub,Dining
20,* Les Family Clinic - health & wellness,Les Family Clinic,Health & Wellness
21,* Payment To Fmc - miscellaneous,Payment To Fmc,Miscellaneous
22,* Sumbul Meats Poultry - food,Sumbul Meats Poultry,Food
23,* Aust Hlth Mgmt Grp P L - miscellaneous,Aust Hlth Mgmt Grp P L,Miscellaneous
24,1. Transfer From Anz Bank - Utility,Transfer From Anz Bank,Utility
25,2. Coles - Groceries,Coles,Groceries
26,3. Velocity Australia - Travel,Velocity Australia,Travel
27,4. Daiso Westfield - Shopping,Daiso Westfield,Shopping
28,5. Ezymart Central - Groceries,Ezymart Central,Groceries
29,6. Agoda Com Aluna Hotel - Travel,Agoda Com Aluna Hotel,Travel
30,7. Chemist Warehouse Westfield - Health,Chemist Warehouse Westfield,Health
31,8. Uber Trip Sydney - Transport,Uber Trip Sydney,Transport
32,9. Yummy Saigon Summer - Food,Yummy Saigon Summer,Food

In [20]:
#check for dup transactions
DupTransDF = CategoriesDF[CategoriesDF.duplicated(subset=['Transaction'], keep=False)]
DupTransDF

Empty DataFrame
Columns: [Transaction - Category, Transaction, Category]
Index: []

In [21]:
#merge model output to the source data before doing text cleaning
SourceDF = TransformedDF.copy()
TestMergeDFs = pd.merge(
    SourceDF,
    CategoriesDF[["Transaction", "Category"]],
    on="Transaction",
    how="left"
)
TestMergeDFs

          Date  Amount                         Transaction           Category
0   27/03/2025    -288               Yarravalleywater Yvow            Utility
1   11/06/2025     -40                    Target Westfield           Shopping
2   02/10/2025    -197                        Barwon Water            Utility
3   22/07/2024   -1500                     Virgin Airlines          Transport
4   27/01/2026     -21            Woolworths Great Western            Grocery
5   15/01/2025     -62                         Service Nsw                NaN
6   19/06/2026    6372               From Metro Art Galary      Entertainment
7   11/11/2024     167                Yellow Bird Painting           Creative
8   01/12/2025     -33                         Aldi Mobile           Shopping
9   04/11/2024    2067  Transfer From Macquarie University          Education
10  17/12/2024    -422                       Fund Transfer            Finance
11  22/04/2024     -17                 Just Ripe Northland               Food
12  25/05/2026     -19           Woolworths Westfield Camp            Grocery
13  27/08/2025      -8                         Aldi Stores            Grocery
14  14/07/2025    -303               Body Sculpting Clinic  Health & Wellness
15  24/12/2024     -51                           Sushi Hub             Dining
16  14/05/2025    -202                   Les Family Clinic  Health & Wellness
17  06/01/2025   -2816                      Payment To Fmc      Miscellaneous
18  30/12/2025      -5                Sumbul Meats Poultry               Food
19  04/10/2024     -70              Aust Hlth Mgmt Grp P L      Miscellaneous
20  07/10/2024    5073              Transfer From Anz Bank            Utility
21  18/05/2026      -1                               Coles          Groceries
22  20/10/2025     -35                  Velocity Australia             Travel
23  30/06/2026     -22                     Daiso Westfield           Shopping
24  08/12/2025      -2                     Ezymart Central          Groceries
25  12/11/2025   -3895               Agoda Com Aluna Hotel             Travel
26  22/10/2025      -5            Woolworths Great Western            Grocery
27  23/07/2024    -137                         Aldi Stores            Grocery
28  21/01/2026    -114         Chemist Warehouse Westfield             Health
29  01/10/2024     -16                    Uber Trip Sydney          Transport
30  09/02/2026     -17                 Yummy Saigon Summer               Food
31  03/03/2026      -7                               Coles          Groceries
32  18/11/2025    -992                       Fund Transfer            Finance

In [ ]:
#Clean up the text in the transaction column to remove leading numbers, asterisks, and extra spaces. 
# Create a new column JoinKey for merging with the categories dataframe. 
# Drop duplicates based on JoinKey and standardise the case of JoinKey to title case.
CategoriesCopyDF = CategoriesDF.copy()
CategoriesCopyDF["Transaction"] = CategoriesCopyDF["Transaction"].fillna("").astype(str).str.strip()
CategoriesCopyDF["Transaction"] = CategoriesCopyDF["Transaction"].str.replace(r"^(\d+\.|\*)\s+", "", 
regex=True)

CategoriesCopyDF["JoinKey"] = CategoriesCopyDF["Transaction"].apply(normalise_transaction)
CategoriesCopyDF = CategoriesCopyDF.drop_duplicates(subset=["JoinKey"], keep="first")
CategoriesCopyDF["JoinKey"] = CategoriesCopyDF["JoinKey"].str.title()

TransformedDF["JoinKey"] = TransformedDF["Transaction"].apply(normalise_transaction)
TransformedDF["JoinKey"] = TransformedDF["JoinKey"].str.title()
TransformedDF
CategoriesCopyDF

CategorisedTrans = pd.merge(
    TransformedDF,
    CategoriesCopyDF[["JoinKey", "Category"]],
    on="JoinKey",
    how="left"
).drop(columns=["JoinKey"])

CategorisedTrans["Category"] = CategorisedTrans["Category"].fillna("Uncategorised")
CategorisedTrans

          Date  Amount                         Transaction           Category
0   27/03/2025    -288               Yarravalleywater Yvow            Utility
1   11/06/2025     -40                    Target Westfield           Shopping
2   02/10/2025    -197                        Barwon Water            Utility
3   22/07/2024   -1500                     Virgin Airlines          Transport
4   27/01/2026     -21            Woolworths Great Western            Grocery
5   15/01/2025     -62                         Service Nsw         Government
6   19/06/2026    6372               From Metro Art Galary      Entertainment
7   11/11/2024     167                Yellow Bird Painting           Creative
8   01/12/2025     -33                         Aldi Mobile           Shopping
9   04/11/2024    2067  Transfer From Macquarie University          Education
10  17/12/2024    -422                       Fund Transfer            Finance
11  22/04/2024     -17                 Just Ripe Northland               Food
12  25/05/2026     -19           Woolworths Westfield Camp            Grocery
13  27/08/2025      -8                         Aldi Stores            Grocery
14  14/07/2025    -303               Body Sculpting Clinic  Health & Wellness
15  24/12/2024     -51                           Sushi Hub             Dining
16  14/05/2025    -202                   Les Family Clinic  Health & Wellness
17  06/01/2025   -2816                      Payment To Fmc      Miscellaneous
18  30/12/2025      -5                Sumbul Meats Poultry               Food
19  04/10/2024     -70              Aust Hlth Mgmt Grp P L      Miscellaneous
20  07/10/2024    5073              Transfer From Anz Bank            Utility
21  18/05/2026      -1                               Coles          Groceries
22  20/10/2025     -35                  Velocity Australia             Travel
23  30/06/2026     -22                     Daiso Westfield           Shopping
24  08/12/2025      -2                     Ezymart Central          Groceries
25  12/11/2025   -3895               Agoda Com Aluna Hotel             Travel
26  22/10/2025      -5            Woolworths Great Western            Grocery
27  23/07/2024    -137                         Aldi Stores            Grocery
28  21/01/2026    -114         Chemist Warehouse Westfield             Health
29  01/10/2024     -16                    Uber Trip Sydney          Transport
30  09/02/2026     -17                 Yummy Saigon Summer               Food
31  03/03/2026      -7                               Coles          Groceries
32  18/11/2025    -992                       Fund Transfer            Finance

In [94]:
CategorisedTrans = CategorisedTrans.dropna()
CategorisedTrans

          Date  Amount                         Transaction           Category
0   27/03/2025    -288               Yarravalleywater Yvow            Utility
1   11/06/2025     -40                    Target Westfield           Shopping
2   02/10/2025    -197                        Barwon Water            Utility
3   22/07/2024   -1500                     Virgin Airlines          Transport
4   27/01/2026     -21            Woolworths Great Western            Grocery
5   15/01/2025     -62                         Service Nsw         Government
6   19/06/2026    6372               From Metro Art Galary      Entertainment
7   11/11/2024     167                Yellow Bird Painting           Creative
8   01/12/2025     -33                         Aldi Mobile           Shopping
9   04/11/2024    2067  Transfer From Macquarie University          Education
10  17/12/2024    -422                       Fund Transfer            Finance
11  22/04/2024     -17                 Just Ripe Northland               Food
12  25/05/2026     -19           Woolworths Westfield Camp            Grocery
13  27/08/2025      -8                         Aldi Stores            Grocery
14  14/07/2025    -303               Body Sculpting Clinic  Health & Wellness
15  24/12/2024     -51                           Sushi Hub             Dining
16  14/05/2025    -202                   Les Family Clinic  Health & Wellness
17  06/01/2025   -2816                      Payment To Fmc      Miscellaneous
18  30/12/2025      -5                Sumbul Meats Poultry               Food
19  04/10/2024     -70              Aust Hlth Mgmt Grp P L      Miscellaneous
20  07/10/2024    5073              Transfer From Anz Bank            Utility
21  18/05/2026      -1                               Coles          Groceries
22  20/10/2025     -35                  Velocity Australia             Travel
23  30/06/2026     -22                     Daiso Westfield           Shopping
24  08/12/2025      -2                     Ezymart Central          Groceries
25  12/11/2025   -3895               Agoda Com Aluna Hotel             Travel
26  22/10/2025      -5            Woolworths Great Western            Grocery
27  23/07/2024    -137                         Aldi Stores            Grocery
28  21/01/2026    -114         Chemist Warehouse Westfield             Health
29  01/10/2024     -16                    Uber Trip Sydney          Transport
30  09/02/2026     -17                 Yummy Saigon Summer               Food
31  03/03/2026      -7                               Coles          Groceries
32  18/11/2025    -992                       Fund Transfer            Finance

In [87]:
UniqCategories = CategorisedTrans['Category'].unique()
UniqCategories

<StringArray>
[          'Utility',          'Shopping',         'Transport',
           'Grocery',        'Government',     'Entertainment',
          'Creative',         'Education',           'Finance',
              'Food', 'Health & Wellness',            'Dining',
     'Miscellaneous',         'Groceries',            'Travel',
            'Health']
Length: 16, dtype: str

In [95]:
def regroup_category():
    # 2. Define a lookup dictionary
    LookupDic = {
        "Food": "Dining & Leisure",
        "Dining": "Dining & Leisure",
        "Entertainment": "Dining & Leisure",
        "Groceries": "Supplies & Essentials",
        "Grocery": "Supplies & Essentials",
        "Shopping": "Retails",
        "Clothing": "Retails",
        "Retail": "Retails",
        "Home": "Shopping & Retails",
        "Utilities": "Utility",
        "Health & Wellness": "Health & Wellness",
        "Health": "Health & Wellness",
        "Travel": "Travel & Transport",
        "Transport": "Travel & Transport"
    }
    CategorisedTrans['Class'] = CategorisedTrans['Category'].map(LookupDic).fillna(CategorisedTrans['Category'])
    return CategorisedTrans

CategorisedTrans = regroup_category()
CategorisedTrans

,Date,Amount,Transaction,Category,Class
0,27/03/2025,-288,Yarravalleywater Yvow,Utility,Utility
1,11/06/2025,-40,Target Westfield,Shopping,Retails
2,02/10/2025,-197,Barwon Water,Utility,Utility
3,22/07/2024,-1500,Virgin Airlines,Transport,Travel & Transport
4,27/01/2026,-21,Woolworths Great Western,Grocery,Supplies & Essentials
5,15/01/2025,-62,Service Nsw,Government,Government
6,19/06/2026,6372,From Metro Art Galary,Entertainment,Dining & Leisure
7,11/11/2024,167,Yellow Bird Painting,Creative,Creative
8,01/12/2025,-33,Aldi Mobile,Shopping,Retails
9,04/11/2024,2067,Transfer From Macquarie University,Education,Education
10,17/12/2024,-422,Fund Transfer,Finance,Finance
11,22/04/2024,-17,Just Ripe Northland,Food,Dining & Leisure
12,25/05/2026,-19,Woolworths Westfield Camp,Grocery,Supplies & Essentials
13,27/08/2025,-8,Aldi Stores,Grocery,Supplies & Essentials
14,14/07/2025,-303,Body Sculpting Clinic,Health & Wellness,Health & Wellness
15,24/12/2024,-51,Sushi Hub,Dining,Dining & Leisure
16,14/05/2025,-202,Les Family Clinic,Health & Wellness,Health & Wellness
17,06/01/2025,-2816,Payment To Fmc,Miscellaneous,Miscellaneous
18,30/12/2025,-5,Sumbul Meats Poultry,Food,Dining & Leisure
19,04/10/2024,-70,Aust Hlth Mgmt Grp P L,Miscellaneous,Miscellaneous
20,07/10/2024,5073,Transfer From Anz Bank,Utility,Utility
21,18/05/2026,-1,Coles,Groceries,Supplies & Essentials
22,20/10/2025,-35,Velocity Australia,Travel,Travel & Transport
23,30/06/2026,-22,Daiso Westfield,Shopping,Retails
24,08/12/2025,-2,Ezymart Central,Groceries,Supplies & Essentials
25,12/11/2025,-3895,Agoda Com Aluna Hotel,Travel,Travel & Transport
26,22/10/2025,-5,Woolworths Great Western,Grocery,Supplies & Essentials
27,23/07/2024,-137,Aldi Stores,Grocery,Supplies & Essentials
28,21/01/2026,-114,Chemist Warehouse Westfield,Health,Health & Wellness
29,01/10/2024,-16,Uber Trip Sydney,Transport,Travel & Transport
30,09/02/2026,-17,Yummy Saigon Summer,Food,Dining & Leisure
31,03/03/2026,-7,Coles,Groceries,Supplies & Essentials
32,18/11/2025,-992,Fund Transfer,Finance,Finance

In [96]:
UniqCategories = CategorisedTrans['Class'].unique()
UniqCategories

<StringArray>
[              'Utility',               'Retails',    'Travel & Transport',
 'Supplies & Essentials',            'Government',      'Dining & Leisure',
              'Creative',             'Education',               'Finance',
     'Health & Wellness',         'Miscellaneous']
Length: 11, dtype: str

In [ ]:
CategorisedTrans = CategorisedTrans.drop(columns=['Category']).rename(columns={'Class': 'Category'})
CategorisedTrans
CategorisedTrans.to_csv('categorised_transactions.csv', index=False)